/* 发音数据 — 英国7日指南（一期：餐厅 + 景点 POI）。
 * IPA 须有权威来源；查不到标 ⚠️ 待确认，绝不编造。src 字段注明来源。
 * key 规则：餐厅用 restaurants.js 的 r.id；POI 用 kebab slug（同地跨天共用去重）。
 * override:{say:"<修正拼写>"} 仅在实测 TTS 读错时添加（"读错的再补"阶段）。
 * nameEn 为朗读文本（& 写作 and、省略破折号，便于 TTS 朗读）+ aria-label。
 * 查询日 2026-09-26。en-GB 英音。4 个并行 subagent 检索 + 交叉核实。 */
window.PRON = {
  // ==================== D1 + D2 ====================
  "st-pancras-international":   { nameEn:"St Pancras International", ipa:"/sənt ˈpæŋkrəs ˌɪntəˈnæʃənəl/", src:"Cambridge 'Pancras'+'saint'+'international'", tricky:true },
  "royal-national-hotel":       { nameEn:"Royal National Hotel",    ipa:"/ˈrɔɪəl ˈnæʃənəl həʊˈtɛl/",      src:"Cambridge 'royal'/'national'/'hotel'" },
  "the-plough":                 { nameEn:"The Plough",              ipa:"/ðə plaʊ/",                       src:"Cambridge 'plough'", tricky:true },
  "british-museum":             { nameEn:"British Museum",         ipa:"/ˈbrɪtɪʃ ˈmjuːziːəm/",           src:"Cambridge 'British'/'museum' + Wikipedia" },
  "russell-square":             { nameEn:"Russell Square",         ipa:"/ˈrʌsəl skwɛə/",                  src:"Collins 'Russell' + Cambridge 'square'" },
  "victoria-station":           { nameEn:"Victoria Station",       ipa:"/vɪkˈtɔːriə ˈsteɪʃən/",           src:"Cambridge 'Victoria'/'station'" },
  "the-jugged-hare":            { nameEn:"The Jugged Hare",        ipa:"/ðə dʒʌɡd heə/",                 src:"Cambridge 'jug'+'hare'; jugged=/dʒʌɡd/; hare non-rhotic /heə/" },
  "kazan":                      { nameEn:"Kazan",                 ipa:"⚠️ 待确认",                       src:"待核实 (London Kazan Restaurant, Turkish-origin; pronunciation unverified)", tricky:true },
  "wetherspoons-the-victoria":  { nameEn:"Wetherspoon's The Victoria", ipa:"/ˈwɛðəspuːnz ðə vɪkˈtɔːriə/", src:"Cambridge 'weather'+'spoon' compound + 'Victoria'", tricky:true },
  "d1-blooms-cafe":             { nameEn:"Blooms Cafe and London Pub", ipa:"/bluːmz ˈkæfeɪ/ + /ˈlʌndən pʌb/", src:"Cambridge 'bloom'+'cafe'+'London'+'pub'" },
  "d1-plough":                  { nameEn:"The Plough",            ipa:"/ðə plaʊ/",                       src:"Cambridge 'plough'", tricky:true },
  "d2-kazan":                   { nameEn:"Kazan Restaurant",      ipa:"⚠️ 待确认",                       src:"待核实", tricky:true },
  "d2-jugged-hare":             { nameEn:"The Jugged Hare",       ipa:"/ðə dʒʌɡd heə/",                 src:"Cambridge 'jug'+'hare'" },
  "d2-wetherspoon-victoria":    { nameEn:"Wetherspoon's The Victoria", ipa:"/ˈwɛðəspuːnz ðə vɪkˈtɔːriə/", src:"Cambridge 'weather'+'spoon' + 'Victoria'", tricky:true },

  // ==================== D3 + D4 (King's Cross + Oxford) ====================
  "kings-cross":                { nameEn:"King's Cross",          ipa:"/kɪŋz krɒs/",                     src:"Cambridge 'king'/'cross'" },
  "bus-stop-t":                 { nameEn:"Bus Stop T",           ipa:"/bʌs stɒp tiː/",                  src:"standard British (bus, stop, letter T)" },
  "platform-9-three-quarters":  { nameEn:"Platform 9 and three quarters", ipa:"/ˈplætfɔːm naɪn ənd θriː ˈkwɔːtəz/", src:"Cambridge (platform, nine, three, quarters)" },
  "german-gymnasium":           { nameEn:"German Gymnasium",      ipa:"/ˈdʒɜːmən dʒɪmˈneɪziəm/",         src:"Cambridge 'German'/'gymnasium'", tricky:true },
  "caravan":                    { nameEn:"Caravan",               ipa:"/ˈkærəvæn/",                      src:"Cambridge 'caravan'" },
  "coal-drops-yard":            { nameEn:"Coal Drops Yard",      ipa:"/kəʊl drɒps ˈjɑːd/",              src:"Cambridge 'coal'/'drops'/'yard'" },
  "gloucester-green":           { nameEn:"Gloucester Green",      ipa:"/ˈɡlɒstə ɡriːn/",                 src:"Cambridge 'Gloucester' (silent 'ce') + 'green'", tricky:true },
  "christ-church":              { nameEn:"Christ Church",         ipa:"/ˌkraɪst ˈtʃɜːtʃ/",               src:"Cambridge 'Christchurch' (Ch in Christ=/k/, Church=/tʃ/)", tricky:true },
  "covered-market":             { nameEn:"Covered Market",        ipa:"/ˈkʌvəd ˈmɑːkɪt/",                src:"Cambridge 'covered'/'market'" },
  "radcliffe-camera":           { nameEn:"Radcliffe Camera",       ipa:"/ˈrædklɪf ˈkæmərə/",              src:"Cambridge 'Radcliffe' + Oxford Learner's 'camera'", tricky:true },
  "bodleian":                   { nameEn:"Bodleian",              ipa:"/ˈbɒdliən/",                      src:"Cambridge 'Bodleian'", tricky:true },
  "bridge-of-sighs":            { nameEn:"Bridge of Sighs",       ipa:"/ˌbrɪdʒ əv ˈsaɪz/",               src:"Cambridge 'bridge'/'of' + Collins 'sigh'" },
  "university-church-st-mary":  { nameEn:"University Church of St Mary the Virgin", ipa:"/ˌjuːnɪˈvɜːsəti tʃɜːtʃ əv sənt ˈmeəri ðə ˈvɜːdʒɪn/", src:"Cambridge (constituents)" },
  "ashmolean-museum":           { nameEn:"Ashmolean Museum",      ipa:"/æʃˈməʊliən mjuːˈziːəm/",         src:"Cambridge 'Ashmolean'/'museum'", tricky:true },
  "d3-caravan":                 { nameEn:"Caravan King's Cross",  ipa:"/ˈkærəvæn kɪŋz krɒs/",            src:"Cambridge 'caravan'/'king'/'cross'" },
  "d3-coal-office":             { nameEn:"Coal Office",          ipa:"/kəʊl ˈɒfɪs/",                    src:"Cambridge 'coal'/'office'" },
  "d3-german-gym":              { nameEn:"German Gymnasium",      ipa:"/ˈdʒɜːmən dʒɪmˈneɪziəm/",         src:"Cambridge 'German'/'gymnasium'", tricky:true },
  "d4-bens-cookies":            { nameEn:"Ben's Cookies",         ipa:"/ˈbenz ˈkʊkɪz/",                  src:"Cambridge 'Ben'/'cookies'" },
  "d4-honest-burgers":          { nameEn:"Honest Burgers",        ipa:"/ˈɒnɪst ˈbɜːɡəz/",                src:"Cambridge 'honest'/'burgers'" },
  "d4-pieminister":             { nameEn:"Pieminister",          ipa:"/ˈpaɪmɪnɪstə/",                   src:"Cambridge 'pie'+'minister' compound" },
  "d4-ashmolean-roof":          { nameEn:"Rooftop Restaurant Ashmolean", ipa:"/ˈruːftɒp ˈrestrɒnt æʃˈməʊliən/", src:"Cambridge 'rooftop'/'restaurant'/'Ashmolean'", tricky:true },
  "d4-sartorelli":              { nameEn:"Sartorelli's Pizza",    ipa:"⚠️ 待确认",                       src:"待核实 (Italian surname; pronunciation unverified)", tricky:true },
  "d4-sasi-thai":               { nameEn:"Sasi's Thai",          ipa:"⚠️ 待确认",                       src:"待核实", tricky:true },
  "d4-grand-cafe":              { nameEn:"The Grand Cafe",        ipa:"/ðə ɡrænd ˈkæfeɪ/",               src:"Cambridge 'the'/'grand'/'cafe'" },
  "d4-turl-st":                 { nameEn:"Turl Street Kitchen",    ipa:"⚠️ 待确认",                       src:"待核实 (Turl locally rhymes with 'curl' but unverified)", tricky:true },

  // ==================== D5 (British Museum + Baker Street) ====================
  "city-sleeper":               { nameEn:"City Sleeper",          ipa:"/ˈsɪti ˈsliːpə/",                 src:"Cambridge 'city'/'sleeper'" },
  "court-cafe":                 { nameEn:"Court Cafe",            ipa:"/kɔːt ˈkæfeɪ/",                   src:"Cambridge 'court'+'cafe' (UK /ˈkæfeɪ/)" },
  "tottenham-court-road":       { nameEn:"Tottenham Court Road",   ipa:"/ˈtɒtənəm kɔːt rəʊd/",            src:"Cambridge 'Tottenham' (UK /ˈtɒtənəm/) + 'court'/'road'", tricky:true },
  "oxford-circus":              { nameEn:"Oxford Circus",         ipa:"/ˈɒksfəd ˈsɜːkəs/",               src:"Cambridge 'Oxford'/'circus'" },
  "baker-street":               { nameEn:"Baker Street",          ipa:"/ˈbeɪkə striːt/",                 src:"Cambridge 'Baker'/'Street'" },
  "sherlock-holmes":            { nameEn:"Sherlock Holmes",       ipa:"/ˈʃɜːlɒk həʊmz/",                 src:"dict.cn/欧路 'Sherlock'/'Holmes' (silent 'l')", tricky:true },
  "pret-a-manger":              { nameEn:"Pret a Manger",        ipa:"/ˌpret ə ˈmɒ̃ʒeɪ/",               src:"Cambridge French 'manger'+ liaison; Oxford Learner's brand entry", tricky:true },
  "daunt-books":                { nameEn:"Daunt Books",           ipa:"/dɔːnt bʊks/",                    src:"Cambridge 'daunt'/'books'" },
  "marylebone-high-street":     { nameEn:"Marylebone High Street", ipa:"/ˈmærələbən haɪ striːt/",         src:"Wikipedia 'Marylebone' (/ˈmærələbən/ non-rhotic) + 'high'/'street'", tricky:true },
  "regents-park":               { nameEn:"Regent's Park",         ipa:"/ˈriːdʒənts pɑːk/",                src:"Cambridge 'Regent'/'Park'" },
  "d5-108-brasserie":           { nameEn:"108 Brasserie and Bar", ipa:"/ˌwʌn əʊ eɪt ˈbræsəri ənd bɑː/",  src:"Cambridge 'brasserie' (UK /ˈbræsəri/) + 'one'/'eight'/'bar'" },
  "d5-court-cafe":              { nameEn:"Court Cafes",           ipa:"/kɔːt ˈkæfeɪz/",                  src:"Cambridge 'cafe' (plural) + 'court'" },
  "cf-dintai":                  { nameEn:"Din Tai Fung",          ipa:"/dɪn taɪ fʊŋ/",                   src:"鼎泰丰 pinyin Dǐng Tàifēng (Baidu Baike) + brand romanization", tricky:true },
  "cf-haidilao":                { nameEn:"Haidilao",             ipa:"/ˌhaɪdiˈlaʊ/",                    src:"海底捞 pinyin hǎi dǐ lāo (Baidu Baike)", tricky:true },
  "cf-lanzhou":                 { nameEn:"Lanzhou Noodle Bar",    ipa:"/ˌlænˈdʒəʊ ˈnuːdl bɑː/",          src:"Hujiang/FRDIC '兰州' pinyin lánzhōu + 'noodle'/'bar'", tricky:true },
  "cf-hotpot":                  { nameEn:"Little Lamb",           ipa:"/ˈlɪtl læm/",                     src:"Cambridge 'little'/'lamb'" },
  "cf-fishchips":               { nameEn:"Poppies",               ipa:"/ˈpɒpiz/",                        src:"Cambridge plural of 'poppy' (UK /ˈpɒpi/)" },
  "d5-store-st-espresso":       { nameEn:"Store Street Espresso",   ipa:"/stɔː striːt eˈspresəʊ/",         src:"Cambridge 'store'/'street'/'espresso'" },
  "d5-the-lamb":                { nameEn:"The Lamb",              ipa:"/ðə læm/",                        src:"Cambridge 'the'/'lamb'" },
  "d5-the-marylebone":          { nameEn:"The Marylebone",        ipa:"⚠️ 待确认",                       src:"店名待核实 (具体门店未确认)" },
  "d5-museum-tavern":           { nameEn:"The Museum Tavern",     ipa:"/ðə mjuːˈziːəm ˈtævən/",          src:"Cambridge 'museum'/'tavern'" },

  // ==================== D6 + D7 (Landmarks + Shopping + Return) ====================
  "london-eye":                 { nameEn:"London Eye",            ipa:"/ˈlʌndən aɪ/",                    src:"Cambridge 'London'/'eye'" },
  "big-ben":                    { nameEn:"Big Ben",               ipa:"/bɪɡ ben/",                       src:"Cambridge 'big'/'Ben'" },
  "borough-market":             { nameEn:"Borough Market",        ipa:"/ˈbʌrə ˈmɑːkɪt/",                 src:"Cambridge 'borough' (UK /ˈbʌrə/, 'ough'→/ə/) + 'market'", tricky:true },
  "tower-bridge":               { nameEn:"Tower Bridge",          ipa:"/ˈtaʊə brɪdʒ/",                   src:"Cambridge 'tower'/'bridge' (non-rhotic)" },
  "bottega-veneta":             { nameEn:"Bottega Veneta",        ipa:"/bɒˈteɪɡə vəˈneɪtə/",              src:"Zhihu luxury-brand guide (anglicised); Italian /botˈtɛːɡa veˈnɛːta/", tricky:true },
  "selfridges":                 { nameEn:"Selfridges",            ipa:"/ˈsɛlfrɪdʒɪz/",                   src:"Cambridge 'self'+'ridge'+ plural /ɪz/ after /dʒ/" },
  "liberty":                    { nameEn:"Liberty",               ipa:"/ˈlɪbəti/",                       src:"Cambridge 'liberty' (UK non-rhotic /ˈlɪbəti/)" },
  "vivienne-westwood":          { nameEn:"Vivienne Westwood",     ipa:"/ˈvɪviən ˈwɛstwʊd/",              src:"danci.gjcha.com 'Vivienne' + Cambridge 'west'/'wood'", tricky:true },
  "neals-yard":                 { nameEn:"Neal's Yard",           ipa:"/niːlz jɑːd/",                    src:"Cambridge 'Neil'(variant 'Neal') + 'yard'", tricky:true },
  "dishoom":                    { nameEn:"Dishoom",               ipa:"/dɪˈʃuːm/",                       src:"Hindi onomatopoeia; Cambridge 'dish'+ /uːm/ (as 'boom')" },
  "the-lighterman":             { nameEn:"The Lighterman",        ipa:"/ðə ˈlaɪtəmən/",                  src:"Cambridge 'the'+'lighter'+'man'" },
  "harrods":                    { nameEn:"Harrods",               ipa:"/ˈhærədz/",                      src:"Oxford ALD 'Harold' vowel analogy + '-ds'=/dz/", tricky:true },
  "d6-borough":                 { nameEn:"Borough Market",        ipa:"/ˈbʌrə ˈmɑːkɪt/",                 src:"Cambridge 'borough'+'market' (same as POI)", tricky:true },
  "d6-dishoom":                 { nameEn:"Dishoom Covent Garden",  ipa:"/dɪˈʃuːm ˈkɒvənt ˈɡɑːdən/",       src:"Cambridge 'dish'+'/uːm/' + iciba 'covent' + Cambridge 'garden'", tricky:true },
  "d6-flat-iron":               { nameEn:"Flat Iron",             ipa:"/flæt ˈaɪən/",                    src:"Cambridge 'flat'/'iron' (UK silent r)", tricky:true },
  "cf-afternoon-tea":           { nameEn:"Fortnum and Mason Diamond Jubilee Tea Salon", ipa:"/ˈfɔːtnəm ənd ˈmeɪsən ˈdaɪmənd ˈdʒuːbɪliː tiː ˈsælɒn/", src:"Cambridge 'fortnum'/'mason'/'diamond'/'jubilee'/'tea'/'salon' (UK)" },
  "d6-hawksmoor":               { nameEn:"Hawksmoor Seven Dials",  ipa:"/ˈhɔːksmʊə ˈsɛvən ˈdaɪəlz/",      src:"Cambridge 'hawk'+'moor'/'seven'/'dial'+plural /z/", tricky:true },
  "cf-english-breakfast":       { nameEn:"Regency Cafe",          ipa:"/ˈriːdʒənsi ˈkæfeɪ/",              src:"Cambridge 'regency'+'cafe'" },
  "d7-harrods-food":            { nameEn:"Harrods Food Halls",     ipa:"/ˈhærədz fuːd hɔːlz/",            src:"Oxford ALD 'Harold' analogy + Cambridge 'food'/'halls'" },
  "d7-lighterman":              { nameEn:"The Lighterman",        ipa:"/ðə ˈlaɪtəmən/",                  src:"Cambridge 'the'+'lighter'+'man' (same as POI)" }
};
