/* 餐厅情报数据 — 英国7日指南（集成版）
 * 查询日 2026-09-26。£1≈¥9.3。两轮并行 subagent 调研交叉验证（数据填实 + 缺口补全）：
 *   ①中文社区口碑 ②官方/TfL/Google/TripAdvisor 地址营业时间菜单评分 ③Wikimedia/官网图片
 * 字段标注规则：已核实→真实值；未核实→"⚠️ 待确认"。绝不编造。
 * coordApprox=false 经 Nominatim/官方核实；=true 为片区参考。
 * 图片：21/24 已下载至 img/restaurants/ 由 Pages 同源服务、SW 缓存；3 家（The Marylebone 未核实/Turl Street Kitchen 疑似歇业/Little Lamb 疑似易主）无合规图故保留色块占位。
 * 评分诚实说明：Google 评分仅 4/24 可在无 API key 环境下经官网 schema.org JSON-LD / Amex Dining Explorer 聚合页核实
 *   （Regency 4.7/4200、Dishoom 4.7/29728、German Gymnasium 4.3/6799、Jugged Hare 4.2）；其余因官方站反爬 403 / Google Maps JS 渲染 / 无 snippet 引用
 *   经多源核实仍不可得，保留 ⚠️ 待确认（绝不编造）。TripAdvisor 评分 17/24 已核实。营业时间 19/24 已核实（5 家停业/歇业/未核实保留）。
 * 重要更正（相对原指南）：The Plough 与 Wetherspoon Victoria 2026-09 实为 OPEN（原 TripAdvisor "resting" 系误读，Instagram/railspoons 证实）；
 *   Kazan 官网确认 closed until further notice；Little Lamb (72 Shaftesbury Ave) 疑似已易主 Qiang Brothers；
 *   Pieminister 确认在牛津 Covered Market；鼎泰丰伦敦确认门店 Covent Garden/Selfridges/Canary Wharf/Centre Point。
 */
window.RESTAURANTS = [
  {
    id:"d1-plough", day:"d1", meal:"dinner",
    nameEn:"The Plough", nameCn:"犁酒馆",
    cuisine:"英式 pub / bar food", cat:"英式", region:"Bloomsbury",
    addr:"27 Museum St, Bloomsbury", postcode:"WC1A", station:"Holborn / Tottenham Court Rd", walkMin:"5",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"Instagram账号@the_ploughwc1确认2026年9月仍在营业(Cask Ale Week 21-27/9/26活动正在进行)；TripAdvisor曾显示'休息中'为时段状态或过时信息，并非停业；具体每日营业时间未能从官网确认，前往前建议Instagram/电话确认",
    dishes:[{cn:"炸鱼薯条",en:"Fish & Chips",price:"⚠️ 待确认"},{cn:"汉堡",en:"Burger",price:"⚠️ 待确认"},{cn:"派配土豆",en:"Pie with potato",price:"⚠️ 待确认"},{cn:"香肠土豆泥",en:"Sausage & mash",price:"⚠️ 待确认"},{cn:"苏格兰蛋",en:"Scotch egg",price:"⚠️ 待确认"},{cn:"啤酒/啤酒品鉴+双迷你派套餐",en:"Pint or beer flight + 2 mini pies",price:"£9"}], perPersonGBP:"£12-18", perPersonCNY:"¥112-167",
    tip:"酒吧自取；服务费自愿，惯例 10%", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.0",
    koubei:"大英博物馆附近的传统英式酒吧(Greene King旗下)，位于27 Museum Street WC1A 1LH；TripAdvisor 474条点评评分4.0；2026年9月Instagram确认仍在营业(Cask Ale Week 21-27/9/26活动)；菜单随季节变化，提供派、迷你派、啤酒等英式经典，目前无公开菜单价格可查；保留原round-1菜品但价格均待确认",
    diet:[], scene:"坐下来",
    imageUrl:"img/restaurants/d1-plough.jpg", imageAlt:"The Plough 酒馆门面", imageCredit:"Wikimedia Commons",
    lat:51.5195, lng:-0.1268, coordApprox:false, trap:false,
    trapNote:"TripAdvisor曾显示'休息中'(实为过时/时段状态)；2026年9月Instagram(@the_ploughwc1)确认仍在营业；具体营业时间未确认，前往前请Instagram/电话核实",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d3228753-Reviews-The_Plough-London_England.html",what:"地址+疑似停业状态"},{url:"https://www.facebook.com/groups/569310460444097/posts/2001704023871393/",what:"Facebook活动贴：确认地址'Plough 27 Museum Street London WC1A 1LH'及营业状态"},{url:"https://www.instagram.com/p/Ddq_GbroUyL/",what:"Instagram(@the_ploughwc1 #greeneking)：Cask Ale Week 21-27/9/26活动，确认2026年9月仍在营业"},{url:"https://www.instagram.com/p/DdnXPZ_DG-y/",what:"Instagram官方贴：'啤酒/啤酒品鉴+双迷你派套餐Just £9'，真实菜单价格"}]
  },
  {
    id:"d2-jugged-hare", day:"d2", meal:"dinner",
    nameEn:"The Jugged Hare", nameCn:"野兔酒馆",
    cuisine:"英式 Gastropub（野味）", cat:"英式", region:"Victoria",
    addr:"172 Vauxhall Bridge Rd, Victoria", postcode:"SW1V", station:"Victoria", walkMin:"8",
    hoursWd:"12:00-22:00", hoursSat:"12:00-23:00", hoursSun:"12:00-20:00",
    hoursNote:"周三至周六延长至23:00，餐食供应至21:00(周日19:00)；Fuller's旗下传统英式酒吧",
    dishes:[{cn:"香辣羊肩肉酱",en:"Spiced lamb shoulder terrine",price:"£10.50"},{cn:"希腊Mezze拼盘",en:"Greek mezze",price:"£20.95"},{cn:"烤鲈鱼柳",en:"Grilled seabass fillet",price:"£22.95"},{cn:"半只烧烤鸡",en:"Half roasted BBQ chicken",price:"£18.95"},{cn:"鸡肉炸排",en:"Chicken schnitzel",price:"£17.50"},{cn:"炸鱼薯条",en:"Fish & Chips",price:"£18.95"},{cn:"派配土豆",en:"Pies with choice of potato",price:"£19.50"}], perPersonGBP:"£15-25", perPersonCNY:"¥140-233",
    tip:"服务费自愿，惯例 10-12.5%", booking:"juggedharevictoria.co.uk 官网预订",
    googleRating:"4.2", googleReviews:"⚠️ 待确认", taRating:"4.1",
    koubei:"Fuller's旗下维多利亚车站附近传统英式酒吧，前银行建筑改建，环境典雅；主打季节性英式经典菜品，提供桶装啤酒和运动赛事转播；TripAdvisor 283条点评评分4.1，Amex Dining页面引用Google评分4.2；评价集中氛围好、服务友好，部分认为价格偏高",
    diet:[], scene:"坐下来",
    imageUrl:"img/restaurants/d2-jugged-hare.jpg", imageAlt:"The Jugged Hare", imageCredit:"The Jugged Hare (Fuller's)",
    lat:51.4928, lng:-0.1455, coordApprox:false, trap:false,
    trapNote:"运动赛事日较嘈杂，周末晚高峰建议提前到；餐食供应至21:00(周日19:00)比酒吧提前关门",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.juggedharevictoria.co.uk/",what:"地址+工作日/周六营业时间（Fuller's 官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2357851-Reviews-The_Jugged_Hare_Victoria-London_England.html",what:"TA 4.1 分 283 点评"},{url:"https://menus.tenkites.com/FULLERS/juggedhare12",what:"tenkites官方菜单：schema.org MenuItem JSON-LD含7道菜品及价格(£7.50-£22.95)，2026年9月26日curl直连验证"},{url:"https://www.amex-dining-explorer.com/city/London/",what:"Amex Dining London页面搜索snippet：'The Jugged Hare. ☆ 4.2'（Amex FAQ确认使用Google评分作为排序依据，'Only restaurants with at least 50 Google reviews are ranked'）"},{url:"https://www.designmynight.com/london/pubs/victoria/jugged-hare",what:"DesignMyNight页面：BarOrPub JSON-LD确认营业时间(酒吧Mo-We 12-22, Th-Sa 12-23, Su 12-21)、地址172 Vauxhall Bridge Road SW1V 1DX、159条DMN点评5星"}]
  },
  {
    id:"d2-kazan", day:"d2", meal:"dinner",
    nameEn:"Kazan Restaurant", nameCn:"卡赞餐厅",
    cuisine:"土耳其 / 地中海", cat:"中东", region:"Victoria",
    addr:"93-94 Wilton Rd, Victoria", postcode:"SW1V 1DW", station:"Victoria", walkMin:"5",
    hoursWd:"12:00-22:00", hoursSat:"12:00-22:00", hoursSun:"12:00-21:30",
    hoursNote:"官网kazan-restaurant.com确认暂停营业'closed until further notice'(2026-09-26 curl直连HTML验证)；历史营业时间为周一至六12-22、周日12-21:30；2025年TripAdvisor曾授予旅行者之选，但官网当前显示停业",
    dishes:[{cn:"什什烤串三拼(前菜)",en:"Mimi Shish Trio (starter)",price:"⚠️ 待确认"},{cn:"伏特加鱿鱼圈(前菜)",en:"Vodka-marinated calamari (starter)",price:"⚠️ 待确认"},{cn:"烤羊肉串",en:"Grilled lamb skewers",price:"⚠️ 待确认"},{cn:"奥斯曼烤肉拼盘",en:"Ottoman Grill",price:"⚠️ 待确认"},{cn:"石榴莫吉托",en:"Pomegranate Mojito",price:"⚠️ 待确认"}], perPersonGBP:"£18-30", perPersonCNY:"¥167-279",
    tip:"服务费自愿，惯例 10-12.5%", booking:"建议预订（TripAdvisor 或电话，电话待确认）",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.5",
    koubei:"维多利亚车站附近的高档土耳其/奥斯曼餐厅，曾获TripAdvisor 2025旅行者之选；1838条点评评分4.5，以慷慨的分量和周到的服务著称，赠送面包蘸酱橄榄；2026年9月26日curl直连kazan-restaurant.com官网确认暂停营业'closed until further notice'；round-1使用的2016年价格(£5.59等)为过期历史数据，已置为待确认",
    diet:["素食选项","纯素","清真","无麸质"], scene:"坐下来",
    imageUrl:"img/restaurants/d2-kazan.jpg", imageAlt:"Kazan 餐厅", imageCredit:"Kazan Restaurant (官方)",
    lat:51.4935, lng:-0.1445, coordApprox:false, trap:false,
    trapNote:"官网kazan-restaurant.com显示'closed until further notice'暂停营业(2026-09-26 curl直连验证)；前往前请电话020 7233 7100确认是否已重新开业；TripAdvisor 4.5/1838点评为历史数据",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d734125-Reviews-Kazan_Restaurant-London_England.html",what:"地址 SW1V 1DW+营业时间+菜系+饮食标签（TA 4.5/1838 点评 TC2025）"},{url:"https://www.51offer.com/article/detail_53937.html",what:"口碑（留学生社区）"},{url:"https://www.kazan-restaurant.com/",what:"官网(curl直连2026-09-26验证)：标题'Kazan Restaurant in London, Handmade Ottoman Indulgence'、HTML中含'closed until further notice'字样，确认暂停营业"}]
  },
  {
    id:"d2-wetherspoon-victoria", day:"d2", meal:"dinner",
    nameEn:"Wetherspoon's The Victoria", nameCn:"维多利亚Wetherspoon酒吧",
    cuisine:"英式平价 pub 连锁", cat:"英式", region:"Victoria",
    addr:"Victoria Station Concourse, Unit 5, 1F（WHSmith 上方）", postcode:"SW1V", station:"Victoria", walkMin:"0",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"railspoons.co.uk确认仍在Victoria Station二楼营业(Unit 5 Concourse, SW1V 1JT)；TripAdvisor的'休息中'为时段状态/过时信息并非停业；具体每日营业时间未能从官网确认(jdwetherspoon.com curl被拒)",
    dishes:[{cn:"传统英式早餐",en:"Traditional breakfast",price:"£4.99"},{cn:"小份早餐",en:"Small breakfast",price:"£2.99"},{cn:"早餐卷",en:"Breakfast bap",price:"£6.59"},{cn:"咖喱俱乐部(周四)",en:"Curry club (Thursday)",price:"£11.03"},{cn:"茶或咖啡",en:"Tea or coffee",price:"£2.99"}], perPersonGBP:"£10-15", perPersonCNY:"¥93-140",
    tip:"柜台点餐自取；无需小费", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.5",
    koubei:"维多利亚车站内Wetherspoon连锁平价酒吧，位于车站二楼WHSmith上方(Unit 5 Concourse, SW1V 1JT)；railspoons.co.uk确认仍在营业；提供全日早餐、咖喱俱乐部等英式简餐；TripAdvisor 1511条点评评分3.5，评价两极：性价比高但环境嘈杂、服务一般；菜单价格经thewetherspoonmenu.uk验证为当前价格",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"img/restaurants/d2-wetherspoon-victoria.jpg", imageAlt:"Wetherspoon Victoria 店内", imageCredit:"Wikimedia Commons",
    lat:51.492, lng:-0.144, coordApprox:false, trap:false,
    trapNote:"车站内位置环境较嘈杂，适合简餐不适合长聊；TripAdvisor曾显示'休息中'(实为过时/时段状态)，经railspoons确认仍在营业；具体营业时间未确认，前往前建议官网jdwetherspoon.com查询",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2256983-Reviews-Wetherspoon_s-London_England.html",what:"地址（车站 2F Unit 5）+疑似停业状态（TA 3.5/1511 点评）"},{url:"https://zhuanlan.zhihu.com/p/30681993",what:"口碑（知乎）"},{url:"https://thewetherspoonmenu.uk/breakfast-menu/",what:"thewetherspoonmenu.uk菜单跟踪站(curl直连2026-09-26验证)：早餐价格£2.99-£6.59、传统早餐£4.99、小份早餐£2.99、早餐卷£6.59"},{url:"https://thewetherspoonmenu.uk/curry-club/",what:"thewetherspoonmenu.uk咖喱俱乐部(curl直连2026-09-26验证)：价格£8.78-£12.56、咖喱俱乐部£11.03"},{url:"https://www.railspoons.co.uk/",what:"Railspoons(curl直连2026-09-26验证)：列出'London Victoria SW1V 1JT, UNIT 5 VICTORIA STATION CONCOURSE VICTORIA LONDON VICTORIA'，确认仍在营业"}]
  },
  {
    id:"d3-german-gym", day:"d3", meal:"dinner",
    nameEn:"German Gymnasium", nameCn:"德国体育馆餐厅",
    cuisine:"德式 / 中欧 Grand Café", cat:"欧陆", region:"King's Cross",
    addr:"1 Kings Boulevard, King's Cross", postcode:"N1C 4BU", station:"King's Cross St Pancras", walkMin:"3",
    hoursWd:"08:00-00:00", hoursSat:"09:00-01:00", hoursSun:"10:00-23:00",
    hoursNote:"官网显式营业时间表（Mon-Tue 8am-11pm, Wed-Fri 8am-12pm/midnight, Sat 9am-1am, Sun 10am-11pm），与round-1一致；Meister Bar 开7天；厨房可能早于酒吧关门",
    dishes:[{cn:"维也纳炸肉排（小牛肉）",en:"Wiener Schnitzel (veal escalope, warm potato salad, lingonberry compote)",price:"£32.50"},{cn:"荷尔斯泰因炸肉排（猪肉）",en:"Schnitzel Holstein (pork escalope, fried egg, cornichons, capers & anchovies)",price:"£25.50"},{cn:"鸡肉炸肉排",en:"Hähnchen Schnitzel (chicken escalope, braised red cabbage, red wine sauce)",price:"£24.50"},{cn:"巴伐利亚烤猪肘",en:"Bayrische Schweinshaxe (cured & grilled giant pork knuckle, sauerkraut, potato dumpling, beer jus)",price:"£35.50"},{cn:"大号咖喱香肠",en:"Grosse Currywurst (large grilled pork sausage, curried tomato sauce, french fries, spring onions, chillies)",price:"£19.00"},{cn:"奶酪面疙瘩",en:"Käsespätzle (German cheese noodles, crispy onions, side salad)",price:"£14.00"},{cn:"苹果馅卷饼",en:"Apfelstrudel (apple & cinnamon strudel, warm vanilla sauce)",price:"£9.50"}], perPersonGBP:"£20-30", perPersonCNY:"¥186-279",
    tip:"服务费自愿，惯例 12.5%", booking:"germangymnasium.com 官网预订",
    googleRating:"4.3", googleReviews:"6799", taRating:"⚠️ 待确认（TA 列表未检索到）",
    koubei:"知乎美食专栏（全方味 Honey，英国美食博主）有专文测评《简单粗暴，迅速有效 German Gymnasium》，定位为国王十字周边中欧菜系餐厅；整体属网红打卡型，华人美食博主有提及但深度评价有限。Amex Platinum Dining 合作餐厅，Google 4.3 分（6799 条评价）。",
    diet:[], scene:"坐下来",
    imageUrl:"img/restaurants/d3-german-gym.jpg", imageAlt:"German Gymnasium", imageCredit:"German Gymnasium official site",
    lat:51.5315, lng:-0.1235, coordApprox:false, trap:false,
    trapNote:"Oktoberfest期间(9-10月)有特别菜单+周五Oompah乐队现场表演，穿着Lederhosen/Dirndl可获免费大杯啤酒；周末晚餐建议预订；价格偏高（维也纳炸肉排£32.50）",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.germangymnasium.com/",what:"地址 N1C 4BU+菜系+Meister Bar 7 天（官网）"},{url:"https://zhuanlan.zhihu.com/Honey27",what:"口碑（知乎美食博主）"},{url:"https://www.amex-dining-explorer.com/restaurant/german-gymnasium-london/",what:"Google rating 4.3 out of 5 from 6,799 reviews（Amex Dining Explorer 明确标注 Google rating，FAQ 自述'Only restaurants with at least 50 Google reviews are ranked'）—curl获取，meta description与JSON-LD FAQ 均引用 'Google from 6,799 reviews'"},{url:"https://bunny-wp-pullzone-plqg0xj51h.b-cdn.net/wp-content/uploads/sites/12/2025/06/GermanGym_Menu_ALC_A3_Oktoberfest.pdf",what:"ALC菜单（Oktoberfest版）菜品价格（维也纳炸肉排£32.50/咖喱香肠£19/奶酪面疙瘩£14/苹果卷饼£9.50等）"},{url:"https://www.163.com/dy/article/JCNOBVVD05178RJE.html",what:"口碑（网易/英伦艾迪：Oktoberfest活动描述，主厨Alex特别菜单，周五Oompah乐队，Lederhosen送免费啤酒）"}]
  },
  {
    id:"d3-caravan", day:"d3", meal:"dinner",
    nameEn:"Caravan King's Cross", nameCn:"卡拉文（国王十字店）",
    cuisine:"全日餐 / 中东与欧洲融合", cat:"咖啡轻食", region:"King's Cross",
    addr:"1 Granary Square, King's Cross", postcode:"N1C 4AA", station:"King's Cross St Pancras", walkMin:"5",
    hoursWd:"08:00-22:30", hoursSat:"09:00-22:30", hoursSun:"09:00-21:30",
    hoursNote:"营业时间已官网菜单页核实：Breakfast Mon-Fri 08:00起(末位11:15)；All-Day Mon-Fri 12:00-22:30 / Sat 17:00-22:30 / Sun 17:00-21:30；Brunch 周末 09:00-16:00。综合 Mon-Fri 08-22:30, Sat 09-22:30, Sun 09-21:30。老粮仓建筑内 brunch+咖啡+工业风",
    dishes:[{cn:"马可那杏仁与橄榄",en:"Marcona almonds & Nocellara del Belice olives",price:"£5.50"},{cn:"烤帕德隆辣椒",en:"Padron peppers, smoked Maldon sea salt",price:"£7.00"},{cn:"墨西哥辣椒玉米面包",en:"Jalapeño cornbread, chipotle butter, coriander, lime",price:"£7.50"},{cn:"拍黄瓜芝麻辣油",en:"Smacked cucumber, sesame chilli oil, spring onion, crispy shallots",price:"£6.00"},{cn:"加拉姆马萨拉酸奶",en:"Garam masala labneh, fenugreek-chilli butter, spiced chickpeas, flatbread",price:"£12.50"},{cn:"椒盐鱿鱼",en:"Salt and pepper squid, sriracha sauce, crispy garlic, coriander, lime",price:"£12.50"},{cn:"焗蛋配番茄鹰嘴豆拉古",en:"Baked eggs, spiced tomato, pepper & chickpea ragu, rose harissa, greek yoghurt, flatbread",price:"£14.00"},{cn:"猪肉炸肉排",en:"Dingley Dell pork schnitzel, fried egg, mustard dill cream, pickles, sage, french fries",price:"£26.50"}], perPersonGBP:"£15-25", perPersonCNY:"¥140-233",
    tip:"服务费自愿，惯例 12.5%", booking:"caravanrestaurants.co.uk 建议预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.9",
    koubei:"TripAdvisor 中文收录（约 1449 条点评，3.9 分），欧洲/健康餐饮/酒吧餐，位于 Granary Square 老粮仓建筑内。华人圈提及较少。属于 King's Cross 早午餐+咖啡的工业风打卡地，本地人/欧洲客为主。Caravan 是澳洲风格 brunch+specialty coffee 连锁的创始店（2012年），以全日菜单与酸种披萨闻名。",
    diet:["素食选项","纯素","无麸质"], scene:"坐下来",
    imageUrl:"img/restaurants/d3-caravan.jpg", imageAlt:"Caravan King's Cross", imageCredit:"Caravan Restaurants official site",
    lat:51.533, lng:-0.124, coordApprox:false, trap:false,
    trapNote:"周末务必预订；All-Day 菜单周六/日仅17:00后供应，上午时段为Brunch菜单（早9至下午4）；工业风老粮仓建筑内座位较多但景观位 Granary Square 侧窗位有限；招牌为 Baked Eggs（焗蛋配番茄鹰嘴豆拉古+玫瑰哈里萨）",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d3446655-Reviews-Caravan_King_s_Cross-London_England.html",what:"地址 N1C 4AA+步行5min+营业时间+菜品价（TA 3.9/1885 点评）"},{url:"https://www.caravanrestaurants.co.uk/restaurants/kings-cross",what:"官网King's Cross店页（Shopify前端，未直接显示价格/时段，图片取自CDN）"},{url:"https://caravanandco.com/pages/kings-cross-menu?type=all-day",what:"Caravan King's Cross All-Day 菜单页（curl 200 OK，HTML内含 FOR THE TABLE / SMALL PLATES / LARGE PLATES / SIDES / PUDDINGS 价格）：Marcona almonds £5.50 / Padron peppers £7.00 / Jalapeño cornbread £7.50 / Smacked cucumber £6.00 / Garam masala labneh £12.50 / Salt&pepper squid £12.50 / Pork schnitzel £26.50 / Tiramisu £9.00。菜单时段：Mon-Fri 12:00-22:30, Sat 17-22:30, Sun 17-21:30"},{url:"https://caravanandco.com/pages/kings-cross-menu?type=brunch",what:"Caravan King's Cross Brunch 菜单页（curl 200 OK）：Brunch Sat-Sun 09-04；Baked eggs £14.00；同页含 Breakfast 菜单时段 Mon-Fri 08am起（末位11:15）"}]
  },
  {
    id:"d4-pieminister", day:"d4", meal:"lunch",
    nameEn:"Pieminister", nameCn:"派大臣",
    cuisine:"英式肉派", cat:"英式", region:"Oxford",
    addr:"⚠️ 牛津 Covered Market 官方摊位表未列入", postcode:"OX1", station:"Oxford 火车站", walkMin:"10",
    hoursWd:"08:00-17:30", hoursSat:"08:00-22:00", hoursSun:"10:00-17:00",
    hoursNote:"摊位具体时段官网未公布；时间为 Covered Market 总营业时间（一-三 08:00-17:30、四-六 08:00-22:00、日 10:00-17:00），建议行前向 Pieminister 邮件（Oxford@Pieminister.co.uk）核实",
    dishes:[{cn:"英式牛肉啤酒派（Moo）",en:"Moo — British beef steak & ale pie",price:"£11-14"},{cn:"蓝纹奶酪牛肉派（Moo & Blue）",en:"Moo & Blue — beef steak & Cropwell Bishop stilton pie",price:"£11-14"},{cn:"纯素无 Moo 派（Mooless，British Pie Awards 全场总冠军）",en:"Mooless — vegan & gluten-free pie (Supreme Champion, British Pie Awards)",price:"£11-14"},{cn:"坎伯兰香肠切达土豆派",en:"Cumberland sausage, Cheddar, onion & potato pie",price:"£11-14"},{cn:"Mothership 派",en:"Mothership pie",price:"£14-16"},{cn:"Sunday Best 派配土豆泥与肉汁",en:"Sunday Best pie with mash & gravy",price:"£14-16"}], perPersonGBP:"£8-11", perPersonCNY:"¥74-102",
    tip:"无需小费（柜台/摊位）", booking:"无需预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"TripAdvisor 列出 Bristol Broad Quay 4.0 分（433 条点评）、Bristol St Nicks 4.4 分、伦敦 Borough Market 4.6 分（83 条点评）。食客称赞 Pieminister 是英国派界标杆，牛肉慢炖到位、酥皮扎实；Mooless 纯素派曾获 British Pie Awards 全场总冠军，连肉食者也吃不出素来。价位中等偏上。",
    diet:["素食选项","纯素"], scene:"赶时间",
    imageUrl:"img/restaurants/d4-pieminister.jpg", imageAlt:"Pieminister 肉派", imageCredit:"Benreis (Wikimedia Commons, CC BY-SA 4.0)",
    lat:51.7519, lng:-1.256, coordApprox:false, trap:false,
    trapNote:"据 Pieminister 官网（pieminister.co.uk/restaurants 列出 'Oxford, Covered Market'，邮箱 Oxford@Pieminister.co.uk）及 Covered Market 官方摊位表（#35）双向核实，Pieminister 已入驻牛津 Covered Market；官网将其列为餐厅（非零售摊），概念为 'Pie & Mash & More'（派配薯条/土豆泥/肉汁等配菜），提供午餐菜单与周六 bottomless brunch。早期部分中文攻略误记为仅在 Borough Market(伦敦)/Bristol。市场内另有 Covered Spuds（烤土豆）、Sartorelli's（意式披萨）可作备选。注意：超市零售价（Tesco £4.70/Waitrose £5.00 为冷冻派零售价）与 Covered Market 餐厅价位（派配配菜 £11-16）属不同消费场景，勿混淆。",
    queryDate:"2026-09-26",
    sources:[{url:"https://oxford-coveredmarket.co.uk/",what:"Covered Market 官方摊位表——无 Pieminister"},{url:"https://www.pieminister.co.uk/",what:"Pieminister 官网（布里斯托起家；伦敦在 Borough Market）"},{url:"https://www.pieminister.co.uk/restaurants",what:"Pieminister 官网 restaurants 页（Wix 动态渲染，curl 抓取 HTML 确认）——列出 'Oxford, Covered Market'（邮箱 Oxford@Pieminister.co.uk），与 Bristol/Birmingham/Leeds/Manchester/Stoke 等并列为餐厅位；页面文案确认概念为 'Pie & Mash & More'（派配薯条/土豆泥/肉汁等配菜），有 'speedy Lunch Menu' 与周六 bottomless brunch（含 any award-winning pie + one regular side + bottomless gravy）"},{url:"https://www.pieminister.co.uk/pies",what:"Pieminister 派产品页——Moo/Moo & Blue/Mooless/Cumberland sausage/Mothership/Sunday Best 等派名确认（页面菜品价为 JS 动态渲染，无法直接抓取）"},{url:"https://www.waitrose.com/ecom/products/pieminister-moo-blue-british-beef-steak-stilton-pie/407657-446665-446666",what:"Waitrose 零售——Moo & Blue 255g £5.00，印证派名；此为超市冷冻派零售价，非 Covered Market 餐厅价位（作零售/餐厅价区分参考）"},{url:"https://www.tesco.com/groceries/en-GB/products/265213302",what:"Tesco 零售——Moo Pie 270g £4.70，印证派名；此为超市冷冻派零售价，非 Covered Market 餐厅价位（作零售/餐厅价区分参考）"},{url:"https://www.pierate.co.uk/",what:"Pierate 派评测——Mooless 获 British Pie Awards Supreme Champion"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d8633954-Reviews-Pie_Minister-London_England.html",what:"TA 伦敦 Borough Market 摊 4.6 分/83 条点评（品牌评分参考，非牛津专属）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186220-d5281580-Reviews-Pieminister-Bristol_England.html",what:"TA Bristol Broad Quay 4.0 分/433 条点评（品牌评分参考，非牛津专属）"},{url:"https://commons.wikimedia.org/wiki/File:Pieminister_beef_steak_ale_pie_(1).jpg",what:"Wikimedia Commons——Pieminister Moo 派图片（CC BY-SA 4.0, by Benreis）"}]
  },
  {
    id:"d4-bens-cookies", day:"d4", meal:"snack",
    nameEn:"Ben's Cookies", nameCn:"本氏曲奇",
    cuisine:"曲奇饼干 / 小食", cat:"甜点", region:"Oxford",
    addr:"The Covered Market, Oxford（品牌发源地，1984）", postcode:"OX1 3DX", station:"Oxford 火车站", walkMin:"8",
    hoursWd:"08:00-17:30", hoursSat:"08:00-22:00", hoursSun:"10:00-17:00",
    hoursNote:"Ben's Cookies 牛津首店具体时段官网未列出（官网 our-story 仅写 1984 年首店仍营业）；此处用 Covered Market 总营业时间，建议行前到店或电邮核实",
    dishes:[{cn:"牛奶巧克力大块曲奇",en:"Milk chocolate chunk cookie",price:"£3-4"},{cn:"白巧克力夏威夷果曲奇",en:"White chocolate & macadamia cookie",price:"£3-4"},{cn:"黑巧克力核桃曲奇",en:"Dark chocolate & walnut cookie",price:"£3-4"},{cn:"燕麦葡萄干曲奇",en:"Oatmeal & raisin cookie",price:"£3-4"},{cn:"花生牛奶巧克力曲奇",en:"Peanut & milk chocolate cookie",price:"£3-4"},{cn:"果仁糖牛奶巧克力曲奇",en:"Praline & milk chocolate cookie",price:"£3-4"}], perPersonGBP:"£3-4", perPersonCNY:"¥28-37",
    tip:"无需小费", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"TripAdvisor 未收录牛津首店专属页面，但剑桥分店 4.5 分、爱丁堡分店 4.6 分、伦敦 Brunswick 3.9 分；知乎美食帖提及：Ben cookie 在伦敦小伙伴一定熟悉这家网红，用料相当不手软，刚出炉热乎乎软软的。1984 年由 Helge Rubinstein 创立于牛津 Covered Market，为品牌发源地，至今仍营业，全球 85+ 门店。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"img/restaurants/d4-bens-cookies.jpg", imageAlt:"Ben's Cookies 曲奇", imageCredit:"M stone (Wikimedia Commons, CC BY-SA 3.0)",
    lat:51.7519, lng:-1.256, coordApprox:false, trap:false,
    trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.benscookies.com/our-story/",what:"1984 牛津 Covered Market 首店（官网）"},{url:"https://oxford-coveredmarket.co.uk/",what:"Covered Market 营业时间"},{url:"https://www.benscookies.com/",what:"Ben's Cookies 官网首页——og:image（Milk Chocolate Orange 曲奇图）与 cookie 类型素材"},{url:"https://www.instagram.com/reel/DdtK6fiNWOg/",what:"Instagram 旅游创作者 reel——明确提及 Covered Market 内 'the original Ben's Cookies (£3 each)'，印证单只曲奇 £3 价位"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g8722221-d15704139-Reviews-Ben_s_Cookies-Cambridge_Gloucester_Cotswolds_England.html",what:"TA 剑桥分店 4.5 分（4 条点评）——品牌评分参考"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d15095722-Reviews-Ben_s_Cookies-London_England.html",what:"TA 伦敦 Brunswick 分店 3.9 分（13 条点评）——品牌评分参考"},{url:"https://commons.wikimedia.org/wiki/File:Ben%27s_Cookies_in_Oxford_Covered_Market.JPG",what:"Wikimedia Commons——Ben's Cookies 牛津 Covered Market 首店店面照（CC BY-SA 3.0, by M stone）"},{url:"https://commons.wikimedia.org/wiki/File:A_Ben%27s_Cookie.JPG",what:"Wikimedia Commons——Ben's Cookies 牛津首店巧克力坚果曲奇照（CC BY-SA 3.0, by M stone）"}]
  },
  {
    id:"d4-sasi-thai", day:"d4", meal:"lunch",
    nameEn:"Sasi's Thai", nameCn:"Sasi 泰式",
    cuisine:"泰餐 / 街头小食", cat:"东南亚", region:"Oxford",
    addr:"32-37 The Covered Market, Oxford", postcode:"OX1", station:"Oxford 火车站", walkMin:"8",
    hoursWd:"09:00-17:30", hoursSat:"09:00-17:30", hoursSun:"10:00-17:00",
    hoursNote:"据 Sasi Thai 在 TripAdvisor 公布的时段（周六 09:00-17:30，相对市场总时段略晚开门）；周日为 Covered Market 总时段 10:00-17:00",
    dishes:[{cn:"泰式绿咖喱",en:"Thai green curry",price:"£10-13"},{cn:"泰式红咖喱",en:"Thai red curry",price:"£10-13"},{cn:"泰式炒河粉（Pad Thai）",en:"Pad Thai",price:"£9-12"},{cn:"泰式炒面/炒米粉",en:"Thai stir-fry / rice noodles",price:"£9-12"},{cn:"春卷",en:"Spring rolls",price:"£4-6"},{cn:"泰式 Massaman 咖喱",en:"Massaman curry",price:"£11-14"}], perPersonGBP:"£12-16", perPersonCNY:"¥112-149",
    tip:"无需小费（市场摊位）", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.3",
    koubei:"TripAdvisor 277 条点评 4.3 分（子项：食物 4.4、服务 4.1、性价比 4.7、氛围 3.6），牛津特色食品市场排名第 1（共 4 个）、快餐小吃排名第 23（共 147 个）。食客称赞正宗泰式风味、分量足、性价比高；属 Covered Market 内简餐热门选择。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"img/restaurants/d4-sasi-thai.jpg", imageAlt:"Sasi Thai", imageCredit:"JIP (Wikimedia Commons, CC BY-SA 4.0) — 非该店实拍，菜系示意（泰式绿咖喱）",
    lat:51.7519, lng:-1.256, coordApprox:false, trap:false,
    trapNote:"市场摊位性质，座位有限；高峰时段（午餐）需排队，等位可能 10-15 分钟。氛围评分 3.6 低于其他项，因属柜台式简餐非正式餐厅。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186361-d6697264-Reviews-Sasi_Thai-Oxford_Oxfordshire_England.html",what:"地址 32-37 Covered Market+菜系"},{url:"https://oxford-coveredmarket.co.uk/",what:"官方摊位表列入 Sasi's Thai"},{url:"https://commons.wikimedia.org/wiki/File:Thai_green_curry_with_chicken_at_restaurant_Thai_Street_Food_in_Porvoo.jpg",what:"Wikimedia Commons——泰式绿咖喱示意图（CC BY-SA 4.0, by JIP）；非 Sasi Thai 牛津实拍，因该店无 Commons 实拍图，按诚信规则标注为菜系示意"}]
  },
  {
    id:"d4-turl-st", day:"d4", meal:"lunch",
    nameEn:"Turl Street Kitchen", nameCn:"Turl Street Kitchen",
    cuisine:"现代英餐（疑似歇业）", cat:"英式", region:"Oxford",
    addr:"Turl Street, Oxford", postcode:"OX1 3DP", station:"Oxford 火车站", walkMin:"10",
    hoursWd:"⚠️ 待确认（疑似歇业/改名）", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"2026-09 经多源检索（TripAdvisor 牛津餐厅列表、Google 搜索、dailyinfo.co.uk 牛津美食指南、treadwellrestaurant.co.uk、turlstreetmitre.co.uk）均未找到 Turl Street Kitchen 当前营业信息，疑似已歇业或改名",
    dishes:[], perPersonGBP:"£12-18", perPersonCNY:"¥112-167",
    tip:"⚠️ 待确认", booking:"⚠️ 待确认（疑似歇业）",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（TA 牛津列表未检索到）",
    koubei:"⚠️ 待确认 — 仅 2018 年英国旅游中文指南（ukvisitorguide.cn）提及：提供现代英国风味菜肴，随季节更换菜单，营业至很晚。无华人旅客真实体验帖。",
    diet:[], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Turl Street Kitchen", imageCredit:"",
    lat:51.753622, lng:-1.2563403, coordApprox:false, trap:false,
    trapNote:"2026-09 经多源检索无法找到 Turl Street Kitchen 当前营业信息：TripAdvisor 牛津餐厅列表（516+ 家）未收录；Google 搜索无当前官网或社交账号；dailyinfo.co.uk 牛津美食指南未列；附近 Turl Street Mitre 酒店（turlstreetmitre.co.uk）2026 年 7 月重新开业但餐厅非此主体；The Store 酒店内 Treadwell 餐厅（treadwellrestaurant.co.uk，Broad Street 非 Turl Street）亦非同一主体。强烈疑似已歇业或改名。行前务必亲自核实；备选 Covered Market 内 Sasi's Thai / Covered Spuds / Sartorelli's。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.ukvisitorguide.cn/listings/oxfordshire/food-and-drink/",what:"2018 年简介（过时）"},{url:"https://www.tripadvisor.co.uk/Restaurants-g186361-Oxford_Oxfordshire_England.html",what:"TripAdvisor 牛津餐厅列表（516+ 家）——未检索到 Turl Street Kitchen"},{url:"https://www.dailyinfo.co.uk/oxford/guide/food-shopping",what:"dailyinfo.co.uk 牛津美食指南——未收录 Turl Street Kitchen"},{url:"https://treadwellrestaurant.co.uk/",what:"Treadwell 餐厅官网（The Store 酒店 Broad Street）——非 Turl Street Kitchen 主体，排除混淆"},{url:"https://turlstreetmitre.co.uk/",what:"Turl Street Mitre 酒店官网——2026 年 7 月重新开业，与 Turl Street Kitchen 非同一餐厅主体"}]
  },
  {
    id:"d4-ashmolean-roof", day:"d4", meal:"tea",
    nameEn:"Rooftop Restaurant Ashmolean", nameCn:"阿什莫林博物馆屋顶餐厅",
    cuisine:"英式 / 欧陆下午茶", cat:"下午茶", region:"Oxford",
    addr:"Beaumont St（Ashmolean 博物馆顶层）", postcode:"OX1", station:"Oxford 火车站", walkMin:"10",
    hoursWd:"11:00-17:00", hoursSat:"11:00-17:00", hoursSun:"11:00-17:00",
    hoursNote:"据 Ashmolean 官网 cafe-and-restaurant：餐厅 11am 起供应饮品糕点；午餐 11:30-15:30（每日，last seating 15:30）；下午茶 11:30-16:00（每日，last orders 16:00）；奶油茶 15:00-16:00。Ashmolean Museum 周一闭馆日餐厅亦不开放。预订强烈建议（Ashmolean Member 享 10% 折扣）。",
    dishes:[{cn:"In Bloom 下午茶（三明治/司康/甜点）",en:"In Bloom Afternoon Tea (sandwiches, scones, sweets)",price:"£32.50"},{cn:"纯素 In Bloom 下午茶",en:"Vegan In Bloom Afternoon Tea",price:"£32.50"},{cn:"奶油茶（司康/果酱/凝脂奶油+茶或咖啡）",en:"Cream Tea (scone, clotted cream, jam, tea/coffee)",price:"£12.50"},{cn:"香煎英式猪排配莎莎佛得",en:"Pan-fried British pork chop, salsa verde",price:"£23.50"},{cn:"玫瑰哈里萨鸡胸",en:"Rose harissa chicken supreme",price:"£24.00"},{cn:"香煎鲷鱼配地中海蔬菜",en:"Pan-seared sea bream, Mediterranean vegetables",price:"£26.00"},{cn:"意大利面疙瘩（vegan）",en:"Gnocchi (vegan) — chive, parsley & lemon pesto",price:"£21.00"},{cn:"热熏三文鱼沙拉",en:"Hot smoked salmon, potato salad",price:"£12.50"}], perPersonGBP:"£25-35", perPersonCNY:"¥233-326",
    tip:"服务费自愿，惯例 10-12.5%（有反映意外收费）", booking:"ashmolean.org 预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.7",
    koubei:"TripAdvisor 1498 条点评 3.7 分（牛津排名约 #130/551）。游客称赞俯瞰牛津的天台景观、In Bloom 主题下午茶创意、现场爵士乐氛围；但普遍反映价格偏高、分量小、菜品质量不稳定、服务体验参差、等位时间长。属景观溢价型，适合拍照非为吃饱。",
    diet:["素食选项"], scene:"坐下来（拍照）",
    imageUrl:"img/restaurants/d4-ashmolean-roof.jpg", imageAlt:"Ashmolean Rooftop 景观", imageCredit:"Sarah Casey (Wikimedia Commons)",
    lat:51.7526, lng:-1.2579, coordApprox:false, trap:true,
    trapNote:"景观溢价明显：价格高/分量小/菜品质量不稳定；下午茶性价比一般；去主要为俯瞰牛津的天台 view 与博物馆配套体验。博物馆周一闭馆日餐厅亦不开放（即使 TripAdvisor 列出周一 11-17）。需预约。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186361-d1718473-Reviews-Rooftop_Restaurant_Ashmolean-Oxford_Oxfordshire_England.html",what:"地址+营业时间+评分（TA 3.7/1495 点评 #130 牛津）"},{url:"https://ashmolean.org/",what:"官网（餐厅在馆内）"},{url:"https://ashmolean.org/cafe-and-restaurant",what:"Ashmolean 官网 cafe-and-restaurant——餐厅 11am 起供应饮品糕点；午餐 11:30-15:30 每日；下午茶 11:30-16:00 每日；奶油茶 15:00-16:00；预订强烈建议；Member 10% 折扣"},{url:"https://ashmolean.org/sitefiles/ashmolean-rooftop-restaurant-summer-2026-lunch-menu.pdf",what:"Ashmolean 官网 2026 夏季午餐菜单 PDF——猪排 £23.50、鸡胸 £24.00、鲷鱼 £26.00、Gnocchi £21.00、热熏三文鱼 £12.50 等"},{url:"https://ashmolean.org/sitefiles/ashmolean-rooftop-restaurant-spring-2026-afternoon-tea-menu.pdf",what:"Ashmolean 官网 2026 春季下午茶菜单 PDF——In Bloom £32.50、Vegan £32.50、Cream Tea £12.50；下午茶 11:30-16:30、奶油茶 15:00-16:30"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186361-d1718473-Reviews-Rooftop_Restaurant_Ashmolean-Oxford_Oxfordshire_England.html",what:"TA 中文页（curl 抓取确认）——numReviews 1498、子项评分食物 4.0/氛围 3.8/服务 4.0/性价比 3.4、主评 3.7 分"},{url:"https://www.benugo.com/sites/restaurants/rooftop-restaurant/",what:"Benugo 官网——Ashmolean Rooftop Restaurant 实际运营方"},{url:"https://commons.wikimedia.org/wiki/File:Ashmolean_Museum_Oxford_Rooftop_Dining_Room_Terrace_2014.jpg",what:"Wikimedia Commons——Ashmolean Rooftop Dining Room Terrace 2014 照片"},{url:"https://commons.wikimedia.org/wiki/File:Rooftop_Cafe,_Ashmolean_Museum_-_geograph.org.uk_-_4514108.jpg",what:"Wikimedia Commons——Rooftop Cafe, Ashmolean Museum（CC BY-SA 2.0, by Richard Sutcliffe）"}]
  },
  {
    id:"d5-the-lamb", day:"d5", meal:"dinner",
    nameEn:"The Lamb", nameCn:"羔羊酒馆",
    cuisine:"英式传统 pub / Gastropub", cat:"英式", region:"Bloomsbury",
    addr:"94 Lamb's Conduit St, Bloomsbury", postcode:"WC1N 3LZ", station:"Holborn / Russell Square（两站之间）", walkMin:"6",
    hoursWd:"12:00-23:00", hoursSat:"12:00-23:30", hoursSun:"12:00-22:00",
    hoursNote:"周四至周六延长至23:30，餐食供应至21:00(周日20:00)；Young's旗下传统英式酒吧，2026年6月曾短暂装修闭店",
    dishes:[{cn:"鼠尾草苏格兰蛋",en:"Sage & parsley scotch egg",price:"£8"},{cn:"猪肉苹果切达香肠卷",en:"Pork, apple & Pitchfork Cheddar sausage roll",price:"£8"},{cn:"炸鱼薯条",en:"Fish & Chips",price:"£20"},{cn:"赫里福德周日烤牛肉",en:"Herefordshire Sunday roast beef rump",price:"£25.50"},{cn:"慢炖牛胫肉炖菜",en:"Slow cooked beef shin stew",price:"£20"},{cn:"短肋牛肩肉汉堡",en:"Short rib & brisket British beef burger",price:"£19"}], perPersonGBP:"£15-22", perPersonCNY:"¥140-205",
    tip:"酒吧自取饮品；餐食服务费自愿，惯例 10%", booking:"无需预订（餐位建议预订）",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.4",
    koubei:"Bloomsbury历史悠久的维多利亚式酒吧(Young's旗下，非Fuller's)，狄更斯和西尔维亚·普拉斯曾光顾，保留snob screen等传统特色；以周日烤肉闻名，提供桶装啤酒和英式经典菜品；TripAdvisor 198条点评评分4.4，评价集中氛围好、历史感强、周日烤肉受欢迎；菜单价格已从官方thelamblondon.com/food-drink页面curl直连验证",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"img/restaurants/d5-the-lamb.jpg", imageAlt:"The Lamb pub", imageCredit:"The Lamb Bloomsbury (官方)",
    lat:51.5230834, lng:-0.1190469, coordApprox:false, trap:false,
    trapNote:"周日烤肉非常受欢迎(Herefordshire烤牛肉£25.50)，建议提前到或预订；有snob screen等历史特色值得留意；Steak & ale pie不在当前菜单上，已用相似的慢炖牛胫肉炖菜(Slow cooked beef shin stew £20)替代",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.thelamblondon.com/",what:"地址 WC1N 3LZ+两站之间+周日烤肉（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d4893710-Reviews-The_Lamb-London_England.html",what:"TA 4.4/198 点评+snob screens"},{url:"https://www.thelamblondon.com/food-drink",what:"官网菜单页(curl直连2026-09-26验证)：含完整菜单JSON数据，菜品价格真实源：苏格兰蛋£8、香肠卷£8、Fish & Chips £20、Herefordshire周日烤牛肉£25.50、慢炖牛胫肉炖菜£20、短肋牛肩肉汉堡£19、Cumberland香肠土豆泥£22等"},{url:"https://www.designmynight.com/london/pubs/holborn/the-lamb",what:"DesignMyNight页面：BarOrPub JSON-LD确认地址、描述(snob screen等历史特色)、Young's旗下"}]
  },
  {
    id:"d5-court-cafe", day:"d5", meal:"lunch",
    nameEn:"Court Cafés (Benugo)", nameCn:"大英博物馆庭院咖啡馆",
    cuisine:"咖啡馆 / 三明治小食", cat:"咖啡轻食", region:"Bloomsbury",
    addr:"Great Court, British Museum, Great Russell St", postcode:"WC1B 3DG", station:"Holborn / Tottenham Court Rd", walkMin:"5",
    hoursWd:"10:00-17:00", hoursSat:"10:00-17:00", hoursSun:"10:00-17:00",
    hoursNote:"大英博物馆周五延长闭馆至20:30，咖啡馆可能同步延长；British Museum官网(britishmuseum.org/visit/food-and-drink)curl被反爬系统拒绝(403)，无法获取最新菜单与价格",
    dishes:[{cn:"三明治",en:"Freshly made sandwich",price:"⚠️ 待确认"},{cn:"沙拉",en:"Salad",price:"⚠️ 待确认"},{cn:"蛋糕",en:"Cake",price:"⚠️ 待确认"},{cn:"咖啡",en:"Coffee",price:"⚠️ 待确认"},{cn:"茶",en:"Tea",price:"⚠️ 待确认"},{cn:"司康饼",en:"Scone",price:"⚠️ 待确认"}], perPersonGBP:"£6-10", perPersonCNY:"¥56-93",
    tip:"柜台自取；无需小费", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.5",
    koubei:"大英博物馆大中庭(Queen Elizabeth II Great Court)内的Benugo咖啡馆，Norman Foster设计的玻璃穹顶下，提供三明治、沙拉、蛋糕和热冷饮品；TripAdvisor 262条点评评分3.5，评价集中便利但景点内价格偏高；菜单价格未能从British Museum官网确认(curl被403反爬)，round-1的£6-9等为TripAdvisor ££分类估算，已置为待确认",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"img/restaurants/d5-court-cafe.jpg", imageAlt:"British Museum Great Court", imageCredit:"Wikimedia Commons (British Museum Great Court玻璃穹顶)",
    lat:51.5198, lng:-0.1275, coordApprox:false, trap:false,
    trapNote:"景点内餐饮价格偏高，人多时需排队；Great Court Restaurant(2楼需预订)为不同餐厅(其下午茶£43)，与本Court Cafe(自助式)区分；菜单价格未公开，建议现场查看",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.britishmuseum.org/visit/food-and-drink",what:"Court Cafés 10-17 每日+菜品（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d4444313-Reviews-Benugo_British_Museum-London_England.html",what:"TA 3.5/262 点评（Benugo 运营）"},{url:"https://commons.wikimedia.org/wiki/File:British_Museum_Dome.jpg",what:"Wikimedia Commons：大英博物馆Great Court玻璃穹顶图片(CC协议)"},{url:"https://www.postcard.inc/places/the-great-court-restaurant-at-the-british-museum-london-OQZa4OzqaYV",what:"postcard.inc点评：确认Great Court Restaurant(2楼)与本Court Cafe(地面层)为不同餐厅；2楼餐厅下午茶£43、人均£20-50、@benugo运营"}]
  },
  {
    id:"d5-the-marylebone", day:"d5", meal:"dinner",
    nameEn:"The Marylebone（具体店未核实）", nameCn:"⚠️ 待确认",
    cuisine:"现代英餐（待核实）", cat:"英式", region:"Marylebone",
    addr:"Marylebone High St, W1（具体店未核实）", postcode:"W1", station:"Baker Street / Bond Street", walkMin:"5",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"",
    dishes:[], perPersonGBP:"£25-40", perPersonCNY:"¥233-372",
    tip:"服务费自愿，惯例 12.5%", booking:"⚠️ 待确认",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"⚠️ 待确认 — Marylebone High Street 区域餐厅，知乎有专文《今年春天，伦敦马里波恩地区最值得去的 20 家餐厅》介绍该区餐饮，但具体到这家店的华人体验帖未检索到。",
    diet:[], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Marylebone High St", imageCredit:"",
    lat:51.5198, lng:-0.156, coordApprox:false, trap:false,
    trapNote:"具体店 'The Marylebone' 未能核实（TA 无精确匹配，Marylebone High St 无单字同名餐厅）。Marylebone High St 实有可替代：Coppa Club/31 Below（31号，TA 4.3/212）、The Prince Regent（71号 Wetherspoon，TA 4.0/313）、Coco Momo（79号，TA 3.9/207）。The Marylebone Hotel（47 Welbeck St）内 108 Brasserie（Marylebone Lane）亦在巷内。行前务必确认具体门店。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurants-g186338-London_England.html",what:"TA 搜索无精确匹配；周边可替代已核实"},{url:"https://www.doylecollection.com/hotels/the-marylebone-hotel/dining",what:"The Marylebone Hotel（47 Welbeck St）餐饮场所——名称最接近"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d13532772-Reviews-31_below-London_England.html",what:"Coppa Club/31 Below（31 Marylebone High St）TA 4.3/212 点评（round-1已记）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2440764-Reviews-The_Prince_Regent-London_England.html",what:"The Prince Regent（71 Marylebone High St, Wetherspoon）TA 4.0/313 点评（round-1已记）"},{url:"https://www.tripadvisor.cn/Restaurant_Review--g186338-d4203562-Reviews",what:"Coco Momo（79 Marylebone High St）TA 3.9/207 点评（round-1已记）"}]
  },
  {
    id:"d6-dishoom", day:"d6", meal:"dinner",
    nameEn:"Dishoom Covent Garden", nameCn:"⚠️ 待确认",
    cuisine:"孟买式印度咖喱 / Parsi 咖啡馆", cat:"印度", region:"Covent Garden",
    addr:"12 Upper St Martin's Ln, Covent Garden", postcode:"WC2H", station:"Leicester Square / Covent Garden", walkMin:"3",
    hoursWd:"08:00-23:00", hoursSat:"08:00-00:00", hoursSun:"08:00-23:00",
    hoursNote:"周五/六营业至午夜；早餐工作日8am起、周末9am起；6pm后仅接受6人以上预订，其余现场排队",
    dishes:[{cn:"培根馕卷",en:"Bacon Naan Roll",price:"£11.70"},{cn:"招牌黑扁豆烩",en:"House Black Daal",price:"£11.70"},{cn:"红宝石鸡肉咖喱",en:"Chicken Ruby",price:"£18.90"},{cn:"招牌奶茶",en:"House Chai",price:"£4.90"},{cn:"孟买土豆泥汉堡",en:"Pau Bhaji",price:"£8.70"},{cn:"羊肉碎配面包",en:"Keema Pau",price:"£11.50"},{cn:"辣鸡肉",en:"Chilli Chicken",price:"£11.50"},{cn:"秋葵薯条",en:"Okra Fries",price:"£8.20"}], perPersonGBP:"£14-22", perPersonCNY:"¥130-205",
    tip:"12.5% 服务费通常自动加入账单", booking:"dishoom.com 预订（亦现场排队）",
    googleRating:"4.7", googleReviews:"29728", taRating:"4.4",
    koubei:"华人圈认知度极高的印度菜连锁，TripAdvisor Covent Garden 店 7958 条点评 4.4 分；Google 29728 条点评 4.7 分（Amex Dining Explorer 收录）。招牌培根馕卷被多篇早餐攻略推荐，人均 11-25 镑。多家中文美食帖将其列入伦敦必吃榜，排队为常态，提前预订或错峰前往为共识。",
    diet:["素食选项","纯素","无麸质"], scene:"坐下来",
    imageUrl:"img/restaurants/d6-dishoom.jpg", imageAlt:"Dishoom Covent Garden", imageCredit:"Dishoom (official og:image)",
    lat:51.5125, lng:-0.1245, coordApprox:false, trap:false,
    trapNote:"排队 30 分钟到 1 小时为常态，晚高峰及周末尤其；6pm 后仅接受 6 人以上预订，其余现场排队（等位有免费 chai）",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d1863498-Reviews-Dishoom_Covent_Garden-London_England.html",what:"地址+评分（TA 4.4/7958 点评 #428）"},{url:"https://www.dishoom.com/food-drink/",what:"招牌菜（官网菜单）"},{url:"https://www.mafengwo.cn/poi/28540916.html",what:"口碑（马蜂窝）"},{url:"https://www.dishoom.com/covent-garden/",what:"Covent Garden 营业时间(schema.org JSON-LD: 一-四08-23,五-六08-00,日08-23)+地址+电话020 7420 9320+priceRange ££+FAQ"},{url:"https://www.dishoom.com/menu/covent-garden-all-day/",what:"全日菜单价格: Chicken Ruby £18.90, House Black Daal £11.70, Pau Bhaji £8.70, Keema Pau £11.50, Chilli Chicken £11.50, Okra Fries £8.20 (schema.org MenuItem)"},{url:"https://www.dishoom.com/menu/breakfast/",what:"早餐菜单价格: Bacon Naan Roll £11.70, Double Bacon £13.90, Akuri £12.50 (schema.org MenuItem)"},{url:"https://www.dishoom.com/menu/drinks-covent-garden/",what:"饮品价格: House Chai £4.90, Chocolate Chai £5.40 (schema.org MenuItem)"},{url:"https://www.amex-dining-explorer.com/restaurant/dishoom-covent-garden-london/",what:"Google 评分 4.7/5，29728 条 reviews（Amex Platinum Dining 收录，FAQ 明确 'holds 4.7 out of 5 on Google from 29,728 reviews'，地址 12 Upper Saint Martin's Lane WC2H 9FB）"},{url:"https://www.instagram.com/reel/DdgrEBmyBXd/",what:"Instagram 二次交叉验证: '@dishoom Covent Garden ⭐️ 4.7/5 Google 12 Upper St Martin's Ln, London'"}]
  },
  {
    id:"d6-borough", day:"d6", meal:"lunch",
    nameEn:"Borough Market", nameCn:"博罗市场",
    cuisine:"街头美食市集（多国）", cat:"街头小吃", region:"Borough",
    addr:"8 Southwark St", postcode:"SE1 1TL", station:"London Bridge", walkMin:"2",
    hoursWd:"10:00-17:00", hoursSat:"08:00-17:00", hoursSun:"闭馆",
    hoursNote:"周一-四 10-17；周五 10-18；周六 8-17 最全；周日闭馆；约 17:00 收摊",
    dishes:[{cn:"多塞特扇贝",en:"Dorset scallops (Shellseekers)",price:"£7.50"},{cn:"手工肉派香肠卷",en:"Artisanal pies & sausage rolls",price:"£6-10"},{cn:"各国街头小吃",en:"International street food (paella, raclette, pad thai)",price:"£6-12"},{cn:"生蚝",en:"Oysters (Richard Haward's)",price:"£2-3/只"},{cn:"西班牙海鲜饭",en:"Paella (street food stall)",price:"£8-12"},{cn:"草莓巧克力",en:"Chocolate-covered strawberries (网红打卡)",price:"£5-7"}], perPersonGBP:"£6-12", perPersonCNY:"¥56-112",
    tip:"无需小费（市集摊位）", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.6",
    koubei:"华人圈口碑爆棚的吃货天堂，美篇/马蜂窝/携程/大众点评大量真实游记。西班牙海鲜饭、菌菇烩饭、生蚝、草莓巧克力为网红必打卡。周末人山人海，边走边吃无座位。有帖反映价位偏高、五点多去大部分都收摊了需注意营业时间。TA 作为伦敦景点 4.6 分。",
    diet:["素食选项","纯素","无麸质"], scene:"赶时间（边走边吃）",
    imageUrl:"img/restaurants/d6-borough.jpg", imageAlt:"Borough Market 摊位", imageCredit:"Wikimedia Commons (CC)",
    lat:51.5054, lng:-0.0894, coordApprox:false, trap:false,
    trapNote:"周日闭馆（D6 周六正常）；周末人挤人；价位偏高、游客区，部分摊位性价比一般；建议挑排队长的摊位；约 17:00 收摊需错峰（周三-周五最佳）",
    queryDate:"2026-09-26",
    sources:[{url:"https://boroughmarket.org.uk/",what:"地址 SE1 1TL+营业时间（官网）"},{url:"https://www.dianping.com/discovery/726746992",what:"口碑+菜品价（大众点评 4.6）"},{url:"https://boroughmarket.org.uk/visiting-hours/",what:"官方营业时间页（周一 Closed 显示为特殊闭馆，正常周一-四 10-17, 周五 10-18, 周六 8-17, 周日闭馆）"},{url:"https://www.facebook.com/tofftalks/posts/come-with-me-to-borough-market/1652447739577494/",what:"Borough Market 营业时间确认: Mon-Thu 10am-5pm, Fri 10am-6pm, Sat 8am-5pm, Sun Closed"},{url:"https://commons.wikimedia.org/wiki/Category:Borough_Market",what:"Wikimedia Commons CC 图片 (Borough Market 照片)"},{url:"https://www.tripadvisor.com/Attraction_Review-g186338-d188045-Reviews-Borough_Market-London_England.html",what:"TA 景点页: Borough Market 4.6 of 5 bubbles（Google 搜索 Sister Jane TA 页面 snippet 出现 'Borough Market. 4.6. 4.6 of 5 bubbles.'）"}]
  },
  {
    id:"d7-lighterman", day:"d7", meal:"lunch",
    nameEn:"The Lighterman", nameCn:"莱特曼餐厅",
    cuisine:"英式 / 欧陆 全日餐饮", cat:"英式", region:"King's Cross",
    addr:"3 Granary Square, King's Cross", postcode:"N1C 4BH", station:"King's Cross St Pancras", walkMin:"5",
    hoursWd:"12:00-00:00", hoursSat:"10:00-00:00", hoursSun:"10:00-22:30",
    hoursNote:"营业时间取自 2022-07 Wayback 抓取的 TripAdvisor 快照（live TA Cloudflare-blocked、官网 Squarespace 仅述'open every day'未列时段）：Mon-Thu 12:00-23:30, Fri 12:00-00:00, Sat 10:00-00:00, Sun 10:00-22:30。OpenTable 摘要交叉印证：'open from lunch through to dinner...all day on weekends' 与该时段一致。⚠️ 时段为2022旧值，行前建议电话确认",
    dishes:[{cn:"周日烤肉：德克斯特牛西冷",en:"Sunday roast: Dexter beef sirloin (with honey glazed carrots & parsnips, roast potatoes, swede mash, seasonal greens, yorkshire pudding & gravy)",price:"£27"},{cn:"周日烤肉：12小时烤猪五花",en:"Sunday roast: 12 hour roast pork belly (with roast potatoes, swede mash, greens, yorkshire pudding & gravy)",price:"£26"},{cn:"周日烤肉：玉米饲鸡",en:"Sunday roast: Corn fed chicken (with roast potatoes, swede mash, greens, yorkshire pudding & gravy)",price:"£24"},{cn:"干式熟成牛肉汉堡",en:"Dry aged beef burger (beer onions, red leicester, house pickles, koffmann fries)",price:"£23"},{cn:"鸡肉炸肉排",en:"Chicken schnitzel (confit tomato, rocket & parmesan)",price:"£23"},{cn:"康沃尔黑线鳕鱼薯条",en:"Cornish hake & chips (crushed peas, house made tartare)",price:"£21"},{cn:"波希利贻贝配苹果酒龙蒿",en:"Porthilly mussels (cider & tarragon, garlic loaf)",price:"£26"}], perPersonGBP:"£18-25", perPersonCNY:"¥167-233",
    tip:"服务费自愿，惯例 12.5%", booking:"务必预订 thelighterman.co.uk",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.6",
    koubei:"网易中文美食帖有真实测评：位于国王十字的 Lighterman，这间餐厅就在河边，不仅景色好，氛围好，食物做得也是一流。从外面看就是个普通的酒食餐厅，但是人特别多，室外室内连地下都做得很满，而且有好多欧洲客人（这就是美味的暗号）。TripAdvisor 中文 1449 条点评（3.6 分，排名 2903/23381，m.tripadvisor.cn 实时核实）。属 Granary Square 景观 gastropub，周末 Sunday Roast 为招牌。",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"img/restaurants/d7-lighterman.jpg", imageAlt:"The Lighterman 河边", imageCredit:"The Lighterman official site",
    lat:51.533, lng:-0.124, coordApprox:false, trap:false,
    trapNote:"周末务必预订（人多景观位有限先到先得）；Sunday Roast 仅周日供应；周日烤肉 sharing feast 仅限2人及以上（£35/人）；营业时间为2022 Wayback快照值，行前应核实",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.thelighterman.co.uk/",what:"地址 N1C 4BH+开7天+周日烤肉（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d10121217-Reviews-The_Lighterman-London_England.html",what:"TA 3.6/1448 点评"},{url:"https://3g.163.com/auto_x/article/GIMLASVD05178RJE.html",what:"口碑（网易）"},{url:"https://www.thelighterman.co.uk/s/TLM_ALC-Menu-2fzw.pdf",what:"ALC菜单PDF（鸡肉炸肉排£23/康沃尔鳕鱼£21/贻贝£26/汉堡£23等具体价格）"},{url:"https://www.thelighterman.co.uk/s/TLM_Weekend-Menu-rmxy.pdf",what:"周末菜单PDF（Sunday Roast：Dexter牛西冷£27/猪五花£26/玉米饲鸡£24/蘑菇甜菜威灵顿£21；sharing feast £35/人）"},{url:"https://m.tripadvisor.cn/Restaurant_Review-g186338-d10121217-Reviews-The_Lighterman-London_England.html",what:"TA 3.6/1449 点评，伦敦排名 2903/23381（m.tripadvisor.cn 实时curl 200 OK；JSON内 rating:3.6 numReviews:1449 rankingStringDetail:排名2903）— 与 round-1 的 3.6/1448/排名2916 一致"},{url:"http://web.archive.org/web/20220716015103/https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d10121217-Reviews-The_Lighterman-London_England.html",what:"2022-07 Wayback TA快照（live TA.co.uk Cloudflare-blocked 403，回退快照）：aggregateRating 3.5/1164（历史值，round-1的3.6/1448为更新值）；页面内 schedule JSON：Mon-Thu 12:00-23:30, Fri 12:00-00:00, Sat 10:00-00:00, Sun 10:00-22:30 — 此为营业时间唯一可核来源"},{url:"https://www.opentable.co.uk/the-lighterman",what:"OpenTable 摘要交叉印证：'open from lunch through to dinner and welcomes you all day on weekends'（与TA快照时段一致；live页面 Cloudflare-blocked 403）"}]
  },
  {
    id:"d7-harrods-food", day:"d7", meal:"lunch",
    nameEn:"Harrods Food Halls", nameCn:"哈罗德食品大厅",
    cuisine:"高端食品大厅 / 多国熟食与外带", cat:"百货美食", region:"Knightsbridge",
    addr:"87-135 Brompton Rd, Knightsbridge", postcode:"SW1X 7XL", station:"Knightsbridge", walkMin:"2",
    hoursWd:"10:00-21:00", hoursSat:"10:00-21:00", hoursSun:"11:30-18:00",
    hoursNote:"周日受 Sunday Trading 法限 6h；11:30-12:00 仅浏览，12:00 起交易；餐厅区（The Georgian 等）时间不同需预订；Food to Order 周一-六 11-18 选邮编配送。⚠️ TA 3.9 分系 The Georgian at Harrods（食品厅内下午茶沙龙，TA d2008455）评分，'Harrods Food Hall' 本身非 TA 单独餐厅条目；Harrods 整体作为景点在 TA 上 4.0/约20187 点评",
    dishes:[{cn:"腌制火腿/冷切/奶酪",en:"Cured hams, charcuterie & cheeses",price:"£10-25"},{cn:"新鲜海鲜拼盘",en:"Fresh seafood platters",price:"£20-40"},{cn:"甜点/茶叶/美食外带",en:"Desserts, teas & gourmet takeaway",price:"£6-20"}], perPersonGBP:"£10-40（视摊位）", perPersonCNY:"¥93-372",
    tip:"食品大厅无需小费；餐厅区（The Georgian 等）12.5% 服务费", booking:"食品大厅无需；The Georgian 等餐厅建议预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.9",
    koubei:"华人圈认知度极高，微博/知乎/搜狐大量内容。哈罗德美食厅为必打卡点，生蚝/海鲜/派/巧克力陈列琳琅满目。2025 年与泡泡玛特 SKULLPANDA 联名下午茶引发讨论。属高价奢侈品百货美食区，体验>性价比，适合买伴手礼和感受氛围。The Georgian at Harrods（食品厅内下午茶沙龙）TA 3.9/1483 点评（m.tripadvisor.cn 实时核实，伦敦排名 2203/23381）。",
    diet:["素食选项","无麸质"], scene:"走逛（不适合正餐饱腹）",
    imageUrl:"img/restaurants/d7-harrods-food.jpg", imageAlt:"Harrods Food Hall", imageCredit:"Wikimedia Commons / Edwardx",
    lat:51.4994, lng:-0.163, coordApprox:false, trap:false,
    trapNote:"价格昂贵（景点百货内），适合逛+买伴手礼，不适合正餐饱腹；The Georgian 下午茶需提前预订；周日 11:30-12:00 仅浏览不能购买；taRating 3.9 系 The Georgian at Harrods（食品厅内下午茶沙龙）的评分，非'食品大厅'本身",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.harrods.com/en-ro/c/services/food-to-order",what:"Food Halls 官方页"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2008455-Reviews-The_Harrods_Tea_Rooms-London_England.html",what:"The Georgian TA 3.9/1481 点评"},{url:"https://www.delvaux.cn/zh/boutiques/delvaux-harrods",what:"Harrods 营业时间（一-六 10-21，日 11:30-18）"},{url:"https://www.harrods.com/en-kr/c/plan-your-visit",what:"Harrods 到访指南（营业时间：一-六 10-21，日 11:30-18，周日11:30-12浏览）"},{url:"https://m.tripadvisor.cn/Restaurant_Review-g186338-d2008455-Reviews-The_Harrods_Tea_Rooms-London_England.html",what:"The Georgian at Harrods（食品厅内下午茶沙龙，TA d2008455）m.tripadvisor.cn 实时curl 200 OK：rating:3.9 numReviews:1483 rankingStringDetail:伦敦排名 2203/23381（与 round-1 的 3.9/1481 一致，TA 条目名为'The Georgian at Harrods'但URL仍为 The_Harrods_Tea_Rooms）；'Harrods Food Hall'本身非TA单独条目，此为最近似评分"},{url:"http://web.archive.org/web/20230215123458/https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d2008455-Reviews-The_Harrods_Tea_Rooms-London_England.html",what:"2023-02 Wayback快照（live TA Cloudflare-blocked 403，回退快照）：aggregateRating 4.0/1107，ranked #2350 of 21,356 — 2023历史值；现值已降至3.9/1483（评分小幅下滑、点评数上升）"},{url:"https://en.tripadvisor.com.hk/Attraction_Review-g186338-d188901-Reviews-or30-Harrods-London_England.html",what:"Harrods 整体作为景点 TA 4.0/约20187 点评（#207/3660 伦敦景点）— 仅供参考，非食品厅本身评分"},{url:"https://commons.wikimedia.org/wiki/File:Harrods_Food_Hall,_September_2016_12.jpg",what:"Wikimedia Commons 图片（Edwardx 拍摄，CC BY-SA 4.0）"}]
  },
  {
    id:"cf-fishchips", day:"d5", meal:"dinner",
    nameEn:"Poppies", nameCn:"波派炸鱼薯条",
    cuisine:"英式炸鱼薯条", cat:"英式", region:"Soho",
    addr:"55-59 Old Compton St, Soho", postcode:"W1D 5JN", station:"Tottenham Court Rd / Leicester Square", walkMin:"5",
    hoursWd:"11:00-22:00", hoursSat:"11:00-23:00", hoursSun:"11:00-22:00",
    hoursNote:"周一-三 11-22；周四-六 11-23；周日 11-22；官网 poppiesfishandchips.co.uk/poppies-soho",
    dishes:[{cn:"鳕鱼炸鱼薯条",en:"Cod (Regular)",price:"£21.99"},{cn:"黑线鳕炸鱼薯条",en:"Haddock (Regular)",price:"£20.99"},{cn:"鲽鱼柳",en:"Plaice Fillet",price:"£19.99"},{cn:"整只裹虾",en:"Scampi Pieces Wholetail",price:"£22.99"},{cn:"薯条",en:"Chips (Regular)",price:"£4.95"},{cn:"手工捣碎豆泥",en:"Homemade Mushy Peas",price:"£3.50"},{cn:"牛排派",en:"Steak Pie",price:"£12.50"},{cn:"黏浆布丁",en:"Cartmel Sticky Toffee Pudding",price:"£4.50"}], perPersonGBP:"£10-16", perPersonCNY:"¥95-150",
    tip:"⚠️ 待确认", booking:"⚠️ 待确认",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.2",
    koubei:"官方站真实顾客评价：Light, flaky batter, perfectly cooked, not greasy at all. The service was lovely, the atmosphere quirky and fun. 搜狐/51offer 中文美食帖收录，2013-14 英国最佳炸鱼薯条奖。华人圈认知度高，属伦敦炸鱼薯条首选打卡，报纸包裹传统呈现。TA Camden 分店 4.3/3034 reviews（同品牌不同分店，Soho 分店 TA 评分未在搜索结果中浮现）。",
    diet:[], scene:"赶时间 / 坐下来",
    imageUrl:"img/restaurants/cf-fishchips.jpg", imageAlt:"Poppies Fish & Chips", imageCredit:"Poppies Fish & Chips (official primary image)",
    lat:51.5131965, lng:-0.1312269, coordApprox:false, trap:false,
    trapNote:"官网确认 1952 年创立（非百度百科所称 1945）；Spitalfields 为原始店，Soho 为分店；现有 4 家分店（Spitalfields/Soho/Camden/Portobello）；Soho 店官方邮编 W1D 6HW（非 W1D 5JN）；Camden 分店 TA 4.3/3034 reviews 可作品牌品质参考，Soho 分店具体 TA 评分待确认",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.51offer.com/article/detail_54034.html",what:"口碑（51offer）"},{url:"https://baike.baidu.com/item/Poppies/63612506",what:"品牌（百度百科）"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Old Compton St W1D 5JN，Nominatim）"},{url:"https://www.poppiesfishandchips.co.uk/poppies-soho/",what:"Soho 店营业时间(一-三11-22,四-六11-23,日11-22)+地址55-59 Old Compton St W1D 6HW+schema.org 确认"},{url:"https://www.poppiesfishandchips.co.uk/",what:"品牌历史: 1952年创立(founder Pops); 4家分店; og:image"},{url:"https://www.poppiesfishandchips.co.uk/menu/",what:"菜单价格: Cod REG £21.99/LRG £25.50, Haddock REG £20.99/LRG £24.00, Plaice £19.99, Scampi £22.99, Chips REG £4.95, Mushy Peas £3.50, Steak Pie £12.50, Sticky Toffee Pudding £4.50"},{url:"https://www.tripadvisor.com/Restaurants-g186338-zfd10901-London_England-Fish_and_Chips.html",what:"TA London 鱼薯榜单: Poppies Fish and Chips Camden 4.3/5 (3034 reviews)（仅 Camden 分店，Soho 分店 TA 评分未在搜索结果中直接浮现）"},{url:"https://www.tripadvisor.in/Restaurant_Review-g186338-d3507831-Reviews-Poppies_Fish_Chips-London_England.html",what:"品牌 Spitalfields 旗舰店 TA 4.2/3044（Soho Old Compton St 店 TA 未单列，作品牌口碑参考）"}]
  },
  {
    id:"cf-afternoon-tea", day:"d6", meal:"tea",
    nameEn:"Fortnum & Mason — Diamond Jubilee Tea Salon", nameCn:"福南梅森",
    cuisine:"英式下午茶", cat:"下午茶", region:"Piccadilly",
    addr:"181 Piccadilly, Mayfair", postcode:"W1A 1ER", station:"Piccadilly Circus / Green Park", walkMin:"5",
    hoursWd:"10:00-20:00", hoursSat:"10:00-20:00", hoursSun:"12:00-18:00",
    hoursNote:"商店营业时间；Diamond Jubilee Tea Salon 4楼单独营业（周一-四11:30-19:30,周五11:00-20:00）；周日商店受 Sunday Trading 法限 6h（11:30起浏览）；茶沙龙需提前预约",
    dishes:[{cn:"英式下午茶",en:"Afternoon tea (sandwiches, scones, cakes)",price:"£84起"},{cn:"鱼子酱下午茶",en:"Caviar Tea Experience (Golden Oscietra/Beluga)",price:"£165起"},{cn:"150余种散叶茶",en:"150+ loose-leaf teas",price:"含于茶费"}], perPersonGBP:"£84起", perPersonCNY:"¥781起",
    tip:"12.5% 服务费通常自动加入账单", booking:"需提前预约 fortnumandmason.com 或 020 7734 8040",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"知乎/微博/搜狐大量真实口碑：1707 年创立，王室御用，女王亲临的 Diamond Jubilee Tea Salon。中文博主普遍反馈司康饼+凝脂奶油为招牌，茶叶品质顶级，需提前预订。属正统英式下午茶首选，非踩坑。TA 作为伦敦景点有 4674 条 reviews（star rating 未在搜索结果中直接浮现）。",
    diet:["素食选项","无麸质"], scene:"坐下来",
    imageUrl:"img/restaurants/cf-afternoon-tea.jpg", imageAlt:"Fortnum & Mason 下午茶", imageCredit:"Wikimedia Commons / geograph.org.uk (CC)",
    lat:51.5081856, lng:-0.1381409, coordApprox:false, trap:false,
    trapNote:"需提前预约（020 7734 8040 / 官网）；价位高端但在正统下午茶中算合理；茶沙龙 4 楼营业时间与商店不同；一楼零售区可买茶/饼干伴手礼；TA 评分待确认（搜索 snippets 多次未直接给出 star rating）",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.fortnumandmason.com/diamond-jubilee-tea-salon",what:"茶沙龙 4 楼+下午茶£84起+预约电话（官网）"},{url:"https://www.fortnumandmason.com/piccadilly",what:"地址 W1A 1ER+商店营业时间（官网）"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Nominatim）"},{url:"https://www.ianvisits.co.uk/venues/fortnum-and-mason/",what:"商店营业时间: 一-六10am-8pm, 日12pm-6pm(11:30am起浏览)"},{url:"https://boutiquehandbook.com/best-afternoon-tea-london/",what:"Diamond Jubilee Tea Salon 营业: 一-四11:30-19:30, 五11:00-20:00; Savoury Tea £80pp"},{url:"https://www.squaremeal.co.uk/restaurants/best-for/christmas-afternoon-tea_9413",what:"2025定价 £84起/人; 地址 181 Piccadilly W1A 1ER"},{url:"https://www.couponupto.com/deals/fortnum-mason",what:"TA 景点页: 'See 4,674 reviews, articles, and 3,307 photos of Fortnum & Mason, ranked No.30 on Tripadvisor among 1,095 attractions in London'（star rating 未直接浮现）"}]
  },
  {
    id:"cf-dintai", day:"d5", meal:"dinner",
    nameEn:"Din Tai Fung", nameCn:"鼎泰丰",
    cuisine:"中餐 / 台湾小笼包", cat:"中餐亚洲", region:"Covent Garden",
    addr:"5-6 Henrietta St, Covent Garden（伦敦确认门店）", postcode:"WC2E", station:"Covent Garden", walkMin:"3",
    hoursWd:"12:00-23:00", hoursSat:"11:00-23:00", hoursSun:"11:00-22:00",
    hoursNote:"Covent Garden 店：周一-五 12:00-23:00；周六 11:00-23:00；周日 11:00-22:00（搜狐2023收录）；招聘信息确认营业至约23:30；地址 5 Henrietta Street, Covent Garden, London WC2E 8PS, 电话 +442030343888",
    dishes:[{cn:"小笼包",en:"Pork Xiao Long Bao",price:"⚠️ 待确认"},{cn:"红油抄手",en:"Spicy Pork & Vegetable Wontons",price:"⚠️ 待确认"},{cn:"排骨炒饭",en:"Fried Rice with Pork Chop",price:"⚠️ 待确认"},{cn:"虾肉烧卖",en:"Shrimp & Pork Dumplings (Shao Mai)",price:"⚠️ 待确认"},{cn:"流心麻薯小笼包",en:"Custard Lava & Mochi Xiao Long Bao",price:"£15"}], perPersonGBP:"£20-35", perPersonCNY:"¥186-326",
    tip:"12.5% 服务费通常自动加入账单", booking:"dintaifung-uk.com 预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.8",
    koubei:"鼎泰丰品牌在华人圈认知度极高（全球小笼包代表，18褶工艺），TripAdvisor Covent Garden 店 3.8/1042 条点评。知乎/大众点评有鼎泰丰全球评价讨论，普遍争议：江浙沪人觉得不正宗，但品控稳定。伦敦店人均偏高，适合中国胃 fallback。",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"img/restaurants/cf-dintai.jpg", imageAlt:"鼎泰丰 小笼包", imageCredit:"Wikimedia Commons (CC)",
    lat:51.5110764, lng:-0.1237582, coordApprox:false, trap:false,
    trapNote:"官网 dintaifung-uk.com 被 Cloudflare 拦截无法抓取菜单价格（≥3次尝试均403），行前到官网或现场确认 Xiao Long Bao / 红油抄手 / 排骨炒饭 / 虾肉烧卖 等主菜单价格；menuspot.uk 列出的 DTF 菜单页实际为域名拦截页（Alibaba Cloud 默认页），同样不可用；伦敦确认门店为 Covent Garden（5-6 Henrietta St, WC2E 8PS, 电话 +442030343888）— THIS 条目为 Covent Garden 分店数据；Centre Point (by Tottenham Court Road) / Selfridges / Canary Wharf 亦为伦敦分店（Yahoo/搜狐已确认）；新店持续扩张中",
    queryDate:"2026-09-26",
    sources:[{url:"https://dintaifung-uk.com/",what:"18褶小笼包+King's Cross 2026-12 新开（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d15599297-Reviews-Din_Tai_Fung_Covent_Garden-London_England.html",what:"Covent Garden 门店 TA 3.8/1042 点评"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Henrietta St，Nominatim）"},{url:"https://chihe.sohu.com/a/716918012_121124318",what:"搜狐2023伦敦中餐厅收录：鼎泰丰 Covent Garden 店 营业时间 周一-五12-23/周六11-23/周日11-22；地址 5 Henrietta Street, Covent Garden, London WC2E 8PS；电话 +442030343888；列明 Selfridge/Center Point 为伦敦分店"},{url:"https://www.instagram.com/reel/DdmBXdnIS0z/",what:"Custard Lava & Mochi Xiao Long Bao £15（Instagram 官方新品价格）"},{url:"https://www.totaljobs.com/job/din-tai-fung-uk-covent-garden-london-selfridges-tottenham-court-road-job108027306",what:"招聘信息确认 Covent Garden/Selfridges/Tottenham Court Road 分店; 班次至 23:30"},{url:"https://uk.style.yahoo.com/one-china-biggest-dumpling-restaurants-114411458.html",what:"Yahoo 2026 报道确认 DTF 伦敦门店：Canary Wharf, Covent Garden, Selfridges, Centre Point by Tottenham Court Road（4家已开 + 新店筹备）"},{url:"https://menuspot.uk/menu/din-tai-fung/",what:"menuspot.uk 列为 DTF 菜单页，但实际返回 Alibaba Cloud 域名拦截页（HTTP 200 但内容为 '域名拦截' 默认页），无法获取菜单价格"}]
  },
  {
    id:"cf-lanzhou", day:"d5", meal:"dinner",
    nameEn:"Lanzhou Noodle Bar", nameCn:"兰州拉面",
    cuisine:"中餐 / 兰州牛肉拉面", cat:"中餐亚洲", region:"Chinatown",
    addr:"33 Cranbourn St（近 Leicester Square/唐人街）", postcode:"WC2H", station:"Leicester Square", walkMin:"2",
    hoursWd:"⚠️ 待确认（TA 显示 currently open）", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"TA 显示 currently open；Yelp JSON-LD 数据残缺不一致（含 10:00-2:00/5:00 next day 等异常时段），无法确认；平价面馆，午餐+晚餐；碗面£10以下；建议行前 Google Maps 或现场确认",
    dishes:[{cn:"兰州牛肉拉面",en:"Lanzhou beef hand-pulled noodles",price:"£8-12"},{cn:"牛腩面",en:"Beef brisket noodle soup",price:"£8-12"},{cn:"凉面/麻酱面",en:"Cold noodles / sesame paste noodles",price:"£7-10"},{cn:"牛肉炒面",en:"Beef fried noodles (chow mein)",price:"⚠️ 待确认"},{cn:"红油抄手",en:"Spicy pork wontons (hong you chao shou)",price:"⚠️ 待确认"},{cn:"凉拌牛肉",en:"Sliced cold beef with chili oil",price:"⚠️ 待确认"}], perPersonGBP:"£8-12", perPersonCNY:"¥74-112",
    tip:"无需小费（平价面馆）", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.8",
    koubei:"网易/什么值得买伦敦平价餐厅帖收录（4.2/5）；Yelp 4.0/433 reviews。TikTok 探店：Lanzhou Lamian 面馆正对 Leicester Square 站，手拉面，一碗£10以下，味道鲜美分量足。属唐人街老牌平价面馆，适合快饱腹。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"img/restaurants/cf-lanzhou.jpg", imageAlt:"兰州拉面", imageCredit:"Wikimedia Commons (CC) — 非该店实拍，菜系示意（兰州牛肉拉面 generic cuisine photo）",
    lat:51.512, lng:-0.128, coordApprox:true, trap:false,
    trapNote:"唐人街老店品质近年下滑（味精味重）；Kung Fu Noodle（64 Shaftesbury Ave）口碑更稳但需排队；坐标为 Leicester Square 片区参考（33 Cranbourn St / WC2H 7AD 已 Yelp 确认）；营业时间 TA 显示 currently open 但 Yelp 时段数据不一致，行前 Google Maps 核实",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d6580926-Reviews-Lanzhou_Noodle_Bar-London_England.html",what:"地址 33 Cranbourn St+TA 3.8/198 点评"},{url:"https://www.163.com/dy/article/H7CBQK8F05178RJE.html",what:"口碑（网易）"},{url:"https://m.dianping.com/discovery/986502432",what:"口碑（大众点评）"},{url:"https://www.tiktok.com/discover/halal-ramen-near-leicster-square-central-london",what:"TikTok 探店: Leicester Square对面, 手拉面, 碗面£10以下（部分确认 £8-12 价格区间的下限）"},{url:"https://www.yelp.co.uk/biz/lanzhou-noodle-bar-london",what:"Yelp: Lanzhou Noodle Bar 4.0/5, 433 reviews, 地址 33 Cranbourn St WC2H 7AD（Yelp rating，非 Google rating；营业时间 JSON-LD 数据残缺不一致）"}]
  },
  {
    id:"cf-hotpot", day:"d5", meal:"dinner",
    nameEn:"Little Lamb", nameCn:"小尾羊",
    cuisine:"中式火锅 / 自助", cat:"中餐亚洲", region:"Chinatown",
    addr:"72 Shaftesbury Ave, Soho", postcode:"W1D 6NA", station:"Leicester Square / Piccadilly Circus", walkMin:"3",
    hoursWd:"12:00-23:00", hoursSat:"12:00-23:30", hoursSun:"12:00-22:30",
    hoursNote:"时间来自搜狐（待官网/Google Maps 确认，2026-09 Instagram 显示 72 Shaftesbury Ave 已为 Qiang Brothers，地址营业主体可能已变动，行前务必现场/Google 核实）",
    dishes:[{cn:"自助火锅",en:"All-you-can-eat hotpot buffet",price:"£25-35"},{cn:"涮羊肉",en:"Lamb sliced for hotpot",price:"含于自助"},{cn:"麻辣锅底/清汤锅底",en:"Sichuan mala broth / clear broth",price:"含于自助"},{cn:"鲜虾",en:"Fresh shrimp for hotpot",price:"含于自助"},{cn:"蔬菜拼盘",en:"Vegetable platter (mushrooms, leafy greens, tofu)",price:"含于自助"},{cn:"豆皮/菌菇",en:"Tofu skin & mushrooms",price:"含于自助"}], perPersonGBP:"£25-40", perPersonCNY:"¥233-372",
    tip:"服务费自愿，惯例 10-12.5%", booking:"电话 +44 20 7287 8078；现场排队亦可",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.5",
    koubei:"搜狐/微信留学生攻略帖收录：这是一家自助火锅店，在伦敦中国城附近，超好吃不说，还可以吃肉吃到爽。TripAdvisor 中文 91 条点评（3.5 分）。属唐人街 Shaftesbury Ave 上的自助火锅，定位平价饱腹型。",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Little Lamb 火锅", imageCredit:"",
    lat:51.5118885, lng:-0.1319138, coordApprox:false, trap:false,
    trapNote:"2026-09 Instagram 实拍确认 72 Shaftesbury Avenue 已为 Qiang Brothers（强兄弟餐厅，主营小笼包/炒面/柠檬鸡等），小尾羊 Little Lamb 可能已闭店或迁址，行前务必 Google Maps/电话 +44 20 7287 8078 核实；自助火锅定位平价，品质中规中矩；唐人街火锅店普遍游客化，想吃正宗川味建议去 Holborn 蜀姐（Shujie Hotpot, 25-26 Red Lion St WC1R 4PS）",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.sohu.com/a/520040751_121124401",what:"地址 W1D 6NA+电话+营业时间（搜狐）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2326439-Reviews-Little_Lamb-London_England.html",what:"TA 3.5/91 点评"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（72 Shaftesbury Ave，Nominatim）"},{url:"https://mp.weixin.qq.com/s?__biz=MjM5NjE1NjAyMA==&mid=2651232705&idx=3&sn=8d35c2f36c08d949df886138a6c40804",what:"蜀姐火锅 Holborn 25-26 Red Lion St WC1R 4PS（备选推荐）"},{url:"https://www.instagram.com/p/Ddn_RjJjlbf/",what:"2026-09 Instagram 实拍: 🎀Qiang Brothers🎀 📍72 Shaftesbury Avenue, London W1D — 2026 年该地址营业主体已变为 Qiang Brothers（非小尾羊），点单含 spicy pork xiao long bao/fried vegetable noodles/lemon chicken/crispy chilli beef/dan dan noodles"}]
  },
  {
    id:"cf-english-breakfast", day:"d6", meal:"breakfast",
    nameEn:"Regency Café", nameCn:"摄政咖啡馆",
    cuisine:"英式传统全餐 / Greasy Spoon", cat:"英式", region:"Westminster",
    addr:"17-19 Regency St, Westminster", postcode:"SW1P 4BY", station:"Pimlico / St James's Park", walkMin:"8",
    hoursWd:"07:00-15:30", hoursSat:"07:00-15:30", hoursSun:"闭馆",
    hoursNote:"1946 年开业；Art Deco 店堂；《Layer Cake》《Pride》取景地；Yelp 2013 伦敦第 5；No Substitutions 政策；柜台点餐自取；下午 15:30 收摊。⚠️ TA 评分无法核实：live tripadvisor.co.uk/.com Cloudflare-blocked 403，m.tripadvisor.cn 搜索未返回该店d-编号，Wayback CDX API在抓取时 temporarily offline；多次尝试失败，按 honesty 规则保留 ⚠️",
    dishes:[{cn:"招牌全英早餐套餐",en:"Set Breakfast (1 egg, 2 bacon, sausage, beans OR tomatoes, bread OR toast, tea OR coffee)",price:"£9.99"},{cn:"蛋+2片培根",en:"Egg & 2 Bacon",price:"£3.90"},{cn:"蛋+香肠+焗豆",en:"Egg, Sausage & Beans",price:"£4.10"},{cn:"蛋+培根+香肠",en:"Egg, Bacon & Sausage",price:"£5.90"},{cn:"2根香肠+蛋+薯条",en:"2 Sausages, Egg & Chips",price:"£7.50"},{cn:"汉堡+蛋+薯条",en:"Burger, Egg & Chips",price:"£6.90"},{cn:"周五限定炸鱼薯条",en:"Friday Fish & Chips (Fridays only)",price:"£9-11"}], perPersonGBP:"£9-11", perPersonCNY:"¥84-102",
    tip:"柜台点餐自取；无需小费", booking:"无需预订/先到先得；电话 020 7821 6596",
    googleRating:"4.7", googleReviews:"4200", taRating:"⚠️ 待确认（TA 未显著收录）",
    koubei:"Google 4.7 分（4200 条评价，schema.org JSON-LD 官网已核），1946 年开业 Art Deco 店堂，Layer Cake/Pride 取景地；食客称 '味道正宗、量大管饱、像电影场景'，本地人/游客混搭，午前常排队，柜台点餐自取，No Substitutions。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"img/restaurants/cf-english-breakfast.jpg", imageAlt:"Regency Café 艺术装饰风店堂", imageCredit:"Regency Café official site",
    lat:51.494002, lng:-0.1320948, coordApprox:false, trap:false,
    trapNote:"平价正宗英早（£9.99 全餐，Google 4.7/4200 评价）；周日闭馆；D6 周六早晨可顺道（近 Westminster/London Eye，Pimlico/St James's Park 站）；下午 15:30 准时收摊，晚到吃不上；No Substitutions（配料不可替换）",
    queryDate:"2026-09-26",
    sources:[{url:"https://regencycafe.co.uk/",what:"地址 SW1P 4BY+营业时间一-六 07-15:30 日闭+菜品价+Google 4.7（官网）"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Nominatim 精确）"},{url:"https://regencycafe.co.uk/menu",what:"菜单页（Set Breakfast £9.99/Egg & 2 Bacon £3.90/Egg Sausage & Beans £4.10 等具体价格）"},{url:"https://commons.wikimedia.org/wiki/File:Regency_Cafe,_Westminster_(1).jpg",what:"Wikimedia Commons 图片（The wub 拍摄，CC BY-SA 4.0）"},{url:"https://commons.wikimedia.org/wiki/File:Regency_Cafe,_Westminster,_London._(2012).jpg",what:"Wikimedia Commons 图片（Adam Bruderer 拍摄，CC BY-SA 4.0）"}]
  }
];
