/* 餐厅情报数据 — 英国7日指南（集成版）
 * 查询日 2026-09-26。£1≈¥9.3。3 个并行 subagent 调研交叉验证：
 *   ①中文社区口碑 ②官方+TfL 地址/营业时间 ③Google/TripAdvisor/OpenTable 评分/招牌菜/预订
 * 字段标注规则：已核实→真实值；未核实→"⚠️ 待确认"。绝不编造。
 * coordApprox=false 经 Nominatim/官方核实；=true 为片区参考。
 * 重要更正（相对原指南）：The Plough/Wetherspoon Victoria 2026-09 疑似停业；Pieminister 不在牛津 Covered Market；
 *   Turl Street Kitchen 疑似歇业；"The Marylebone" 具体店未核实；鼎泰丰 Center Point 未核实（确认店在 Covent Garden）。
 * 图片：Wikimedia 等直链未能获取，卡片以菜系色块占位（onerror 降级），不编造图片 URL。
 */
window.RESTAURANTS = [
  {
    id:"d1-plough", day:"d1", meal:"dinner",
    nameEn:"The Plough", nameCn:"⚠️ 待确认",
    cuisine:"英式 pub / bar food", cat:"英式", region:"Bloomsbury",
    addr:"27 Museum St, Bloomsbury", postcode:"WC1A", station:"Holborn / Tottenham Court Rd", walkMin:"5",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"⚠️ 2026-09 TripAdvisor 显示 resting/疑似停业，营业时间不可得，行前务必核实",
    dishes:[], perPersonGBP:"£12-18", perPersonCNY:"¥112-167",
    tip:"酒吧自取；服务费自愿，惯例 10%", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（474 条点评未显示星级）",
    koubei:"⚠️ 待确认 — TripAdvisor 中文有收录（酒吧餐/英国菜，伦敦排名约 1314），但未检索到华人旅客深度体验帖。大英博物馆周边传统英式酒馆，定位游客区便利型 pub。",
    diet:[], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"The Plough 酒馆门面", imageCredit:"",
    lat:51.5195, lng:-0.1268, coordApprox:false, trap:false,
    trapNote:"⚠️ 2026-09 TripAdvisor 显示 resting/疑似停业，行前务必核实！D1 深夜抵达备选：酒店内 Blooms Café/London Pub，或打车至唐人街（Piccadilly→Leicester Sq）。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d3228753-Reviews-The_Plough-London_England.html",what:"地址+疑似停业状态"}]
  },
  {
    id:"d2-jugged-hare", day:"d2", meal:"dinner",
    nameEn:"The Jugged Hare", nameCn:"⚠️ 待确认",
    cuisine:"英式 Gastropub（野味）", cat:"英式", region:"Victoria",
    addr:"172 Vauxhall Bridge Rd, Victoria", postcode:"SW1V", station:"Victoria", walkMin:"8",
    hoursWd:"周一-二 12:00-22:00；周三-五 12:00-23:00", hoursSat:"12:00-23:00", hoursSun:"⚠️ 待确认",
    hoursNote:"Fuller's 官网；建议预订，晚高峰易满",
    dishes:[{en:"Seasonal game dishes",cn:"时令野味",price:"⚠️ 待确认"},{en:"Refined pub classics",cn:"精致酒吧经典菜",price:"£15-25"},{en:"Cask ales / craft beers",cn:"桶装艾尔/精酿啤酒",price:"⚠️ 待确认"}],
    perPersonGBP:"£15-25", perPersonCNY:"¥140-233",
    tip:"服务费自愿，惯例 10-12.5%", booking:"juggedharevictoria.co.uk 官网预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.1",
    koubei:"⚠️ 待确认 — TripAdvisor 中文收录（4.1 分，283 条点评，酒吧餐/英国菜），华人旅客深度体验帖未检索到。Victoria 周边 gastropub，猎物/野味菜系为卖点。",
    diet:[], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"The Jugged Hare", imageCredit:"",
    lat:51.4928, lng:-0.1455, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.juggedharevictoria.co.uk/",what:"地址+工作日/周六营业时间（Fuller's 官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2357851-Reviews-The_Jugged_Hare_Victoria-London_England.html",what:"TA 4.1 分 283 点评"}]
  },
  {
    id:"d2-kazan", day:"d2", meal:"dinner",
    nameEn:"Kazan Restaurant", nameCn:"⚠️ 待确认",
    cuisine:"土耳其 / 地中海", cat:"中东", region:"Victoria",
    addr:"93-94 Wilton Rd, Victoria", postcode:"SW1V 1DW", station:"Victoria", walkMin:"5",
    hoursWd:"12:00-22:00", hoursSat:"12:00-22:00", hoursSun:"12:00-21:30",
    hoursNote:"⚠️ 待官网确认 — 时间来自 TripAdvisor（第三方）；Travellers' Choice 2025；晚上人多需预订",
    dishes:[{en:"Mimi Shish Trio (starter)",cn:"三式烤肉串拼盘",price:"⚠️ 待确认"},{en:"Sea Bream on garlic mash & spinach",cn:"海鲷配蒜蓉薯泥菠菜",price:"⚠️ 待确认"},{en:"Complimentary warm breads, dips & olives",cn:"免费热面包蘸酱橄榄",price:"免费"},{en:"Lychee Martini",cn:"荔枝马天尼",price:"⚠️ 待确认"}],
    perPersonGBP:"£18-30", perPersonCNY:"¥167-279",
    tip:"服务费自愿，惯例 10-12.5%", booking:"建议预订（TripAdvisor 或电话，电话待确认）",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.5",
    koubei:"华人留学生圈有真实探店报告：Wilton Road 上的土耳其餐厅，装潢餐具服务都很专业，晚上人多需提前预订；调酒师会主动让客人试饮刚调好的鸡尾酒。整体评价偏高档商务聚餐型，非平价快餐。",
    diet:["素食选项","纯素","清真","无麸质"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Kazan 餐厅", imageCredit:"",
    lat:51.4935, lng:-0.1445, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d734125-Reviews-Kazan_Restaurant-London_England.html",what:"地址 SW1V 1DW+营业时间+菜系+饮食标签（TA 4.5/1838 点评 TC2025）"},{url:"https://www.51offer.com/article/detail_53937.html",what:"口碑（留学生社区）"}]
  },
  {
    id:"d2-wetherspoon-victoria", day:"d2", meal:"dinner",
    nameEn:"Wetherspoon's The Victoria", nameCn:"⚠️ 待确认",
    cuisine:"英式平价 pub 连锁", cat:"英式", region:"Victoria",
    addr:"Victoria Station Concourse, Unit 5, 1F（WHSmith 上方）", postcode:"SW1V", station:"Victoria", walkMin:"0",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"⚠️ 2026-09 TripAdvisor 显示 resting/疑似停业，营业时间不可得",
    dishes:[{en:"Traditional English breakfast",cn:"传统英式早餐",price:"£6-9"},{en:"Pub classics (burger, fish & chips, curry)",cn:"酒吧经典（汉堡/炸鱼薯条/咖喱）",price:"£10-15"},{en:"Cask ale / coffee",cn:"桶装艾尔/咖啡",price:"£3-5"}],
    perPersonGBP:"£10-15", perPersonCNY:"¥93-140",
    tip:"柜台点餐自取；无需小费", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.5",
    koubei:"Wetherspoon 连锁在华人留学生圈口碑一致：平价英式酒吧菜代表，All Day Full English 用 Spode 蓝花瓷盘盛，周二 Steak Club/周四 Curry Club/周日 Sunday Roast 约 7.99 镑。Victoria 车站 2F 店为旅客便利型，性价比高但无精致度可言。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"⚠️ 待确认", imageAlt:"Wetherspoon Victoria 店内", imageCredit:"",
    lat:51.4920, lng:-0.1440, coordApprox:false, trap:false,
    trapNote:"⚠️ 2026-09 TripAdvisor 显示 resting/疑似停业，行前务必核实。备选：Victoria 站内/周边 Pret、Upper Crust 或其他 pub。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2256983-Reviews-Wetherspoon_s-London_England.html",what:"地址（车站 2F Unit 5）+疑似停业状态（TA 3.5/1511 点评）"},{url:"https://zhuanlan.zhihu.com/p/30681993",what:"口碑（知乎）"}]
  },
  {
    id:"d3-german-gym", day:"d3", meal:"dinner",
    nameEn:"German Gymnasium", nameCn:"⚠️ 待确认",
    cuisine:"德式 / 中欧 Grand Café", cat:"欧陆", region:"King's Cross",
    addr:"1 Kings Boulevard, King's Cross", postcode:"N1C 4BU", station:"King's Cross St Pancras", walkMin:"3",
    hoursWd:"⚠️ 待确认（Meister Bar 开 7 天；具体时段待官网）", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"工业风历史建筑（伦敦首座体操馆）；早晨咖啡、夜晚鸡尾酒+深夜饮品；全日菜单",
    dishes:[{en:"Wiener Schnitzel",cn:"维也纳炸肉排（号称 London's finest）",price:"⚠️ 待确认"},{en:"German sausages / Würste",cn:"德式香肠",price:"⚠️ 待确认"},{en:"German tortes & Kaffee und Kuchen",cn:"德式蛋糕与下午咖啡",price:"⚠️ 待确认"},{en:"German Pilsner",cn:"德国皮尔森啤酒",price:"⚠️ 待确认"}],
    perPersonGBP:"£20-30", perPersonCNY:"¥186-279",
    tip:"服务费自愿，惯例 12.5%", booking:"germangymnasium.com 官网预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（TA 列表未检索到）",
    koubei:"知乎美食专栏（全方味 Honey，英国美食博主）有专文测评《简单粗暴，迅速有效 German Gymnasium》，定位为国王十字周边中欧菜系餐厅。整体属网红打卡型，华人美食博主有提及但深度评价有限。",
    diet:[], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"German Gymnasium", imageCredit:"",
    lat:51.5315, lng:-0.1235, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.germangymnasium.com/",what:"地址 N1C 4BU+菜系+Meister Bar 7 天（官网）"},{url:"https://zhuanlan.zhihu.com/Honey27",what:"口碑（知乎美食博主）"}]
  },
  {
    id:"d3-caravan", day:"d3", meal:"dinner",
    nameEn:"Caravan King's Cross", nameCn:"⚠️ 待确认",
    cuisine:"全日餐 / 中东与欧洲融合", cat:"咖啡轻食", region:"King's Cross",
    addr:"1 Granary Square, King's Cross", postcode:"N1C 4AA", station:"King's Cross St Pancras", walkMin:"5",
    hoursWd:"周一-五 08:00-22:30", hoursSat:"09:00-22:30", hoursSun:"09:00-21:30",
    hoursNote:"⚠️ 待官网确认 — 时间来自 TripAdvisor（第三方）；老粮仓建筑内，brunch+咖啡",
    dishes:[{en:"Marcona almonds & Nocellara olives",cn:"马可那杏仁与橄榄",price:"£5.50"},{en:"Padron peppers, smoked Maldon salt",cn:"烤帕德隆辣椒",price:"£6.00"},{en:"Jalapeño cornbread, chipotle butter",cn:"墨西哥辣椒玉米面包",price:"£7.50"},{en:"Smacked cucumber, sesame chilli oil",cn:"拍黄瓜芝麻辣油",price:"£5.80"}],
    perPersonGBP:"£15-25", perPersonCNY:"¥140-233",
    tip:"服务费自愿，惯例 12.5%", booking:"caravanrestaurants.co.uk 建议预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.9",
    koubei:"TripAdvisor 中文收录（1885 条点评，3.9 分），欧洲/健康餐饮/酒吧餐，位于 Granary Square 老粮仓建筑内。华人圈提及较少。属于 King's Cross 早午餐+咖啡的工业风打卡地，本地人/欧洲客为主。",
    diet:["素食选项","纯素","无麸质"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Caravan King's Cross", imageCredit:"",
    lat:51.5330, lng:-0.1240, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d3446655-Reviews-Caravan_King_s_Cross-London_England.html",what:"地址 N1C 4AA+步行5min+营业时间+菜品价（TA 3.9/1885 点评）"}]
  },
  {
    id:"d4-pieminister", day:"d4", meal:"lunch",
    nameEn:"Pieminister", nameCn:"⚠️ 待确认",
    cuisine:"英式肉派", cat:"英式", region:"Oxford",
    addr:"⚠️ 牛津 Covered Market 官方摊位表未列入", postcode:"OX1", station:"Oxford 火车站", walkMin:"10",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"⚠️ 重大存疑：牛津 Covered Market 官方摊位表无 Pieminister；其确认门店在 Borough Market（伦敦）/Bristol",
    dishes:[{en:"英式肉派（冷/热）",cn:"meat pie",price:"£8-11"}],
    perPersonGBP:"£8-11", perPersonCNY:"¥74-102",
    tip:"无需小费（柜台/摊位）", booking:"无需预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"⚠️ 待确认 — 牛津 Covered Market 内英式肉派专门店，华人旅客体验帖未检索到。品牌布里斯托起家，主打冷热肉派。",
    diet:["素食选项","纯素"], scene:"赶时间",
    imageUrl:"⚠️ 待确认", imageAlt:"Pieminister 肉派", imageCredit:"",
    lat:51.7519, lng:-1.2560, coordApprox:false, trap:false,
    trapNote:"⚠️ 牛津 Covered Market 官方摊位表未列入 Pieminister（其确认门店在 Borough Market 伦敦 / Bristol St Nicholas Market）。行前务必核实；可改市场内 Covered Spuds、Sartorelli's 等其他派摊。",
    queryDate:"2026-09-26",
    sources:[{url:"https://oxford-coveredmarket.co.uk/",what:"Covered Market 官方摊位表——无 Pieminister"},{url:"https://www.pieminister.co.uk/",what:"Pieminister 官网（布里斯托起家；伦敦在 Borough Market）"}]
  },
  {
    id:"d4-bens-cookies", day:"d4", meal:"snack",
    nameEn:"Ben's Cookies", nameCn:"⚠️ 待确认",
    cuisine:"曲奇饼干 / 小食", cat:"甜点", region:"Oxford",
    addr:"The Covered Market, Oxford（品牌发源地，1984）", postcode:"OX1 3DX", station:"Oxford 火车站", walkMin:"8",
    hoursWd:"⚠️ 待确认（Covered Market 一至三 08-17:30）", hoursSat:"⚠️ 待确认（市场四-六 08-22:00）", hoursSun:"⚠️ 待确认（市场日 10-17:00）",
    hoursNote:"市场总营业时间：一至三 08:00-17:30、四至六 08:00-22:00、日 10:00-17:00；各摊位有差异，以 Ben's 当日为准",
    dishes:[{en:"Chocolate chunk cookie",cn:"巧克力大块曲奇",price:"£3-4"},{en:"White chocolate & cranberry cookie",cn:"白巧克力蔓越莓曲奇",price:"£3-4"},{en:"Oatmeal & raisin cookie",cn:"燕麦葡萄干曲奇",price:"£3-4"}],
    perPersonGBP:"£3-4", perPersonCNY:"¥28-37",
    tip:"无需小费", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"知乎美食帖提及：Ben cookie 在伦敦小伙伴一定熟悉这家网红 Ben cookie，用料相当不手软，刚出炉热乎乎软软的。1984 年创立于牛津 Covered Market，为品牌发源地，华人圈认知度高，必打卡零食型，价格亲民。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"⚠️ 待确认", imageAlt:"Ben's Cookies 曲奇", imageCredit:"",
    lat:51.7519, lng:-1.2560, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.benscookies.com/our-story/",what:"1984 牛津 Covered Market 首店（官网）"},{url:"https://oxford-coveredmarket.co.uk/",what:"Covered Market 营业时间"}]
  },
  {
    id:"d4-sasi-thai", day:"d4", meal:"lunch",
    nameEn:"Sasi's Thai", nameCn:"⚠️ 待确认",
    cuisine:"泰餐 / 街头小食", cat:"东南亚", region:"Oxford",
    addr:"32-37 The Covered Market, Oxford", postcode:"OX1", station:"Oxford 火车站", walkMin:"8",
    hoursWd:"⚠️ 待确认（市场总时段见 Ben's 条）", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"官方摊位表列入 Sasi's Thai；市场内简餐",
    dishes:[{en:"Thai curries (red/green)",cn:"泰式红/绿咖喱",price:"£12-16"},{en:"Pad Thai",cn:"泰式炒河粉",price:"£12-16"},{en:"Thai stir-fry / noodles",cn:"泰式炒面",price:"£12-16"}],
    perPersonGBP:"£12-16", perPersonCNY:"¥112-149",
    tip:"无需小费（市场摊位）", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（277 条点评，牛津特色食品市场排名第1，星级未显示）",
    koubei:"TripAdvisor 中文收录（277 条点评），牛津 Covered Market 内泰国菜快餐，价位偏低。华人旅客深度评价帖未检索到，属市场内简餐选择。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"⚠️ 待确认", imageAlt:"Sasi Thai", imageCredit:"",
    lat:51.7519, lng:-1.2560, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186361-d6697264-Reviews-Sasi_Thai-Oxford_Oxfordshire_England.html",what:"地址 32-37 Covered Market+菜系"},{url:"https://oxford-coveredmarket.co.uk/",what:"官方摊位表列入 Sasi's Thai"}]
  },
  {
    id:"d4-turl-st", day:"d4", meal:"lunch",
    nameEn:"Turl Street Kitchen", nameCn:"⚠️ 待确认",
    cuisine:"现代英餐（疑似歇业）", cat:"英式", region:"Oxford",
    addr:"Turl Street, Oxford", postcode:"OX1 3DP", station:"Oxford 火车站", walkMin:"10",
    hoursWd:"⚠️ 待确认（疑似歇业/改名）", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"⚠️ 2026-09 无法在 TripAdvisor 牛津餐厅列表或官网找到，疑似已歇业/改名",
    dishes:[], perPersonGBP:"£12-18", perPersonCNY:"¥112-167",
    tip:"⚠️ 待确认", booking:"⚠️ 待确认（疑似歇业）",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（TA 牛津列表未检索到）",
    koubei:"⚠️ 待确认 — 仅 2018 年英国旅游中文指南（ukvisitorguide.cn）提及：提供现代英国风味菜肴，随季节更换菜单，营业至很晚。无华人旅客真实体验帖。",
    diet:[], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Turl Street Kitchen", imageCredit:"",
    lat:51.753622, lng:-1.2563403, coordApprox:false, trap:false,
    trapNote:"⚠️ 2026-09 无法在 TripAdvisor 牛津餐厅列表或官网找到 Turl Street Kitchen，疑似已歇业/改名。行前务必核实；备选 Covered Market 内 Sasi's Thai / Covered Spuds / Sartorelli's。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.ukvisitorguide.cn/listings/oxfordshire/food-and-drink/",what:"2018 年简介（过时）"}]
  },
  {
    id:"d4-ashmolean-roof", day:"d4", meal:"tea",
    nameEn:"Rooftop Restaurant Ashmolean", nameCn:"阿什莫林博物馆屋顶餐厅",
    cuisine:"英式 / 欧陆下午茶", cat:"下午茶", region:"Oxford",
    addr:"Beaumont St（Ashmolean 博物馆顶层）", postcode:"OX1", station:"Oxford 火车站", walkMin:"10",
    hoursWd:"11:00-17:00（下午茶 11:30-16:00）", hoursSat:"11:00-17:00", hoursSun:"11:00-17:00",
    hoursNote:"⚠️ 待官网确认 — 时间来自 TripAdvisor（第三方，2026-09 更新）；有现场爵士乐；周四正常开放",
    dishes:[{en:"Afternoon tea (sandwiches, scones, cakes)",cn:"下午茶（三明治/司康/蛋糕）",price:"£25-35"},{en:"Seasonal lunch plates",cn:"时令午餐",price:"£15-25"},{en:"Creative cakes & pastries",cn:"创意蛋糕甜点",price:"£6-10"}],
    perPersonGBP:"£25-35", perPersonCNY:"¥233-326",
    tip:"服务费自愿，惯例 10-12.5%（有反映意外收费）", booking:"ashmolean.org 预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.7",
    koubei:"TripAdvisor 中文 1495 条点评（3.7 分，牛津排名 130）。游客称赞俯瞰牛津的景观和氛围（有现场爵士乐），但普遍反映价格偏高、分量小、有意外收费，菜品质量不稳定，服务体验参差、等位时间长。下午茶和创意蛋糕获正面评价。属景观溢价型，适合拍照非为吃饱。",
    diet:["素食选项"], scene:"坐下来（拍照）",
    imageUrl:"⚠️ 待确认", imageAlt:"Ashmolean Rooftop 景观", imageCredit:"",
    lat:51.7526, lng:-1.2579, coordApprox:false, trap:true,
    trapNote:"景观溢价明显：价格高/分量小/有额外收费；下午茶性价比一般；去主要为俯瞰牛津的天台 view",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurant_Review-g186361-d1718473-Reviews-Rooftop_Restaurant_Ashmolean-Oxford_Oxfordshire_England.html",what:"地址+营业时间+评分（TA 3.7/1495 点评 #130 牛津）"},{url:"https://ashmolean.org/",what:"官网（餐厅在馆内）"}]
  },
  {
    id:"d5-the-lamb", day:"d5", meal:"dinner",
    nameEn:"The Lamb", nameCn:"⚠️ 待确认",
    cuisine:"英式传统 pub / Gastropub", cat:"英式", region:"Bloomsbury",
    addr:"94 Lamb's Conduit St, Bloomsbury", postcode:"WC1N 3LZ", station:"Holborn / Russell Square（两站之间）", walkMin:"6",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认（周日烤肉营业）",
    hoursNote:"百年 pub；Sunday Roast 招牌；亦作 D4 返回后晚餐备选；snob screens（维多利亚挡酒板）",
    dishes:[{en:"Pub classics (pie, fish & chips)",cn:"酒吧经典（肉派/炸鱼薯条）",price:"£15-22"},{en:"Cask ales",cn:"桶装艾尔啤酒",price:"£4-6"},{en:"Sunday roast",cn:"周日烤肉",price:"£15-22"}],
    perPersonGBP:"£15-22", perPersonCNY:"¥140-205",
    tip:"酒吧自取饮品；餐食服务费自愿，惯例 10%", booking:"无需预订（餐位建议预订）",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.4",
    koubei:"⚠️ 待确认 — The Lamb 为 Bloomsbury 百年历史 pub（官网自称伦敦最古老酒馆之一，狄更斯/Plath 曾光顾），以 Sunday Roast 和 cask ales 闻名。华人旅客深度体验帖未检索到。",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"The Lamb pub", imageCredit:"",
    lat:51.5230834, lng:-0.1190469, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.thelamblondon.com/",what:"地址 WC1N 3LZ+两站之间+周日烤肉（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d4893710-Reviews-The_Lamb-London_England.html",what:"TA 4.4/198 点评+snob screens"}]
  },
  {
    id:"d5-court-cafe", day:"d5", meal:"lunch",
    nameEn:"Court Cafés (Benugo)", nameCn:"⚠️ 待确认",
    cuisine:"咖啡馆 / 三明治小食", cat:"咖啡轻食", region:"Bloomsbury",
    addr:"Great Court, British Museum, Great Russell St", postcode:"WC1B 3DG", station:"Holborn / Tottenham Court Rd", walkMin:"5",
    hoursWd:"10:00-17:00", hoursSat:"10:00-17:00", hoursSun:"10:00-17:00",
    hoursNote:"馆内营业，随博物馆开放（周五延至 20:30）；Great Court 9:00 开；另 Great Court Restaurant 11:30-17:00",
    dishes:[{en:"Fresh sandwiches",cn:"新鲜三明治",price:"£6-10"},{en:"Salads",cn:"沙拉",price:"£6-10"},{en:"Cakes & hot/cold drinks",cn:"蛋糕与冷热饮",price:"£3-6"}],
    perPersonGBP:"£6-10", perPersonCNY:"¥56-93",
    tip:"柜台自取；无需小费", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.5",
    koubei:"⚠️ 待确认 — 大英博物馆 Great Court 内 Court Café（Benugo 运营），华人旅客具体评价帖未检索到。属博物馆内便利餐饮，参观间隙简餐咖啡，价格预期偏高（景点内）。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"⚠️ 待确认", imageAlt:"British Museum Great Court", imageCredit:"",
    lat:51.5198, lng:-0.1275, coordApprox:false, trap:false, trapNote:"景点内价格偏高",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.britishmuseum.org/visit/food-and-drink",what:"Court Cafés 10-17 每日+菜品（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d4444313-Reviews-Benugo_British_Museum-London_England.html",what:"TA 3.5/262 点评（Benugo 运营）"}]
  },
  {
    id:"d5-the-marylebone", day:"d5", meal:"dinner",
    nameEn:"The Marylebone（具体店未核实）", nameCn:"⚠️ 待确认",
    cuisine:"现代英餐（待核实）", cat:"英式", region:"Marylebone",
    addr:"Marylebone High St, W1（具体店未核实）", postcode:"W1", station:"Baker Street / Bond Street", walkMin:"5",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"⚠️ 具体店铺未核实；Marylebone High St 富人区精致餐饮聚集地",
    dishes:[], perPersonGBP:"£25-40", perPersonCNY:"¥233-372",
    tip:"服务费自愿，惯例 12.5%", booking:"⚠️ 待确认",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"⚠️ 待确认 — Marylebone High Street 区域餐厅，知乎有专文《今年春天，伦敦马里波恩地区最值得去的 20 家餐厅》介绍该区餐饮，但具体到这家店的华人体验帖未检索到。",
    diet:[], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Marylebone High St", imageCredit:"",
    lat:51.5198, lng:-0.1560, coordApprox:false, trap:false,
    trapNote:"⚠️ 具体店铺 'The Marylebone' 未能核实（TripAdvisor 无精确匹配）。Marylebone High St 实有可替代：Coppa Club/31 Below（31 号，TA 4.3/212）、The Prince Regent（71 号 Wetherspoon，TA 4.0/313）、Coco Momo（79 号，TA 3.9）。行前确认具体门店。",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.co.uk/Restaurants-g186338-London_England.html",what:"TA 搜索无精确匹配；周边可替代已核实"},{url:"https://www.doylecollection.com/hotels/the-marylebone-hotel/dining",what:"The Marylebone Hotel（47 Welbeck St）餐饮场所——名称最接近"}]
  },
  {
    id:"d6-dishoom", day:"d6", meal:"dinner",
    nameEn:"Dishoom Covent Garden", nameCn:"⚠️ 待确认",
    cuisine:"孟买式印度咖喱 / Parsi 咖啡馆", cat:"印度", region:"Covent Garden",
    addr:"12 Upper St Martin's Ln, Covent Garden", postcode:"WC2H", station:"Leicester Square / Covent Garden", walkMin:"3",
    hoursWd:"⚠️ 待官网确认（King's Cross 参照：一-四 08-23）", hoursSat:"⚠️ 待官网确认（参照 09-00）", hoursSun:"⚠️ 待官网确认（参照 09-23）",
    hoursNote:"官网 dishoom.com；排队为常态，建议错峰或预约；早/午/晚/brunch/夜宵",
    dishes:[{en:"House Black Daal",cn:"招牌黑扁豆烩",price:"⚠️ 待确认"},{en:"Chicken Ruby",cn:"红宝石鸡肉咖喱",price:"⚠️ 待确认"},{en:"Bacon Naan Roll",cn:"培根馕卷",price:"⚠️ 待确认"},{en:"Masala Chai",cn:"玛莎拉奶茶",price:"⚠️ 待确认"}],
    perPersonGBP:"£14-22", perPersonCNY:"¥130-205",
    tip:"12.5% 服务费通常自动加入账单", booking:"dishoom.com 预订（亦现场排队）",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"4.4",
    koubei:"华人圈认知度极高的印度菜连锁，TripAdvisor 中文 Covent Garden 店 7958 条点评（4.4 分，伦敦排名 428），马蜂窝国王十字店 3.6 分。招牌培根馕卷被多篇早餐攻略推荐，人均 11-25 镑。多家中文美食帖将其列入伦敦必吃榜，排队为常态，提前预订或错峰前往为共识。属高性价比网红，非踩坑店。",
    diet:["素食选项","纯素","无麸质"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Dishoom Covent Garden", imageCredit:"",
    lat:51.5125, lng:-0.1245, coordApprox:false, trap:false, trapNote:"排队久，错峰前往",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d1863498-Reviews-Dishoom_Covent_Garden-London_England.html",what:"地址+评分（TA 4.4/7958 点评 #428）"},{url:"https://www.dishoom.com/food-drink/",what:"招牌菜（官网菜单）"},{url:"https://www.mafengwo.cn/poi/28540916.html",what:"口碑（马蜂窝）"}]
  },
  {
    id:"d6-borough", day:"d6", meal:"lunch",
    nameEn:"Borough Market", nameCn:"博罗市场",
    cuisine:"街头美食市集（多国）", cat:"街头小吃", region:"Borough",
    addr:"8 Southwark St", postcode:"SE1 1TL", station:"London Bridge", walkMin:"2",
    hoursWd:"周一-四 10:00-17:00；周五 10:00-18:00", hoursSat:"08:00-17:00（最全）", hoursSun:"闭馆（周日休）",
    hoursNote:"⚠️ 周日闭馆；周六最全；周三-周五最佳错峰；约 17:00 收摊",
    dishes:[{en:"Dorset scallops (Shellseekers)",cn:"多塞特扇贝",price:"£7.50/3只"},{en:"Artisanal pies & sausage rolls",cn:"手工肉派香肠卷",price:"£6-10"},{en:"International street food (paella, raclette, pad thai)",cn:"各国街头小吃",price:"£6-12"}],
    perPersonGBP:"£6-12", perPersonCNY:"¥56-112",
    tip:"无需小费（市集摊位）", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"华人圈口碑爆棚的吃货天堂，美篇/马蜂窝/携程/大众点评大量真实游记。西班牙海鲜饭（Bomba Paella）10 镑一份、菌菇烩饭、生蚝（Richard Haward's）、草莓巧克力为网红必打卡。周末人山人海，边走边吃无座位。有帖反映价位偏高、五点多去大部分都收摊了需注意营业时间。属必去但需错峰（周三-周五最佳）。",
    diet:["素食选项","纯素","无麸质"], scene:"赶时间（边走边吃）",
    imageUrl:"⚠️ 待确认", imageAlt:"Borough Market 摊位", imageCredit:"",
    lat:51.5054, lng:-0.0894, coordApprox:false, trap:false,
    trapNote:"价位偏高、游客区，周末人挤人；部分摊位性价比一般（如巧克力草莓），建议挑排队长的摊位；⚠️ 周日闭馆（D6 周六正常）",
    queryDate:"2026-09-26",
    sources:[{url:"https://boroughmarket.org.uk/",what:"地址 SE1 1TL+营业时间（官网）"},{url:"https://www.dianping.com/discovery/726746992",what:"口碑+菜品价（大众点评 4.6）"}]
  },
  {
    id:"d7-lighterman", day:"d7", meal:"lunch",
    nameEn:"The Lighterman", nameCn:"⚠️ 待确认",
    cuisine:"英式 / 欧陆 全日餐饮", cat:"英式", region:"King's Cross",
    addr:"3 Granary Square, King's Cross", postcode:"N1C 4BH", station:"King's Cross St Pancras", walkMin:"5",
    hoursWd:"⚠️ 待确认（开 7 天；具体时段待官网）", hoursSat:"⚠️ 待确认（周末早午餐）", hoursSun:"⚠️ 待确认（周日烤肉全天）",
    hoursNote:"河边景观；三层楼；周末早午餐+ Bloody Mary +周日烤肉全天；dog-friendly",
    dishes:[{en:"Sunday roast (beef, Yorkshire pudding)",cn:"周日烤肉（牛肉+约克郡布丁）",price:"£18-25"},{en:"Seasonal British mains",cn:"时令英式主菜",price:"£15-22"},{en:"Breakfast / brunch",cn:"早餐/早午餐",price:"£10-14"}],
    perPersonGBP:"£18-25", perPersonCNY:"¥167-233",
    tip:"服务费自愿，惯例 12.5%", booking:"务必预订 thelighterman.co.uk",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.6",
    koubei:"网易中文美食帖有真实测评：位于国王十字的 Lighterman，这间餐厅就在河边，不仅景色好，氛围好，食物做得也是一流。从外面看就是个普通的酒食餐厅，但是人特别多，室外室内连地下都做得很满，而且有好多欧洲客人（这就是美味的暗号）。TripAdvisor 中文 1448 条点评（3.6 分，排名 2916）。属 Granary Square 景观 gastropub，周末 Sunday Roast 为招牌。",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"The Lighterman 河边", imageCredit:"",
    lat:51.5330, lng:-0.1240, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.thelighterman.co.uk/",what:"地址 N1C 4BH+开7天+周日烤肉（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d10121217-Reviews-The_Lighterman-London_England.html",what:"TA 3.6/1448 点评"},{url:"https://3g.163.com/auto_x/article/GIMLASVD05178RJE.html",what:"口碑（网易）"}]
  },
  {
    id:"d7-harrods-food", day:"d7", meal:"lunch",
    nameEn:"Harrods Food Halls", nameCn:"哈罗德食品大厅",
    cuisine:"高端食品大厅 / 多国熟食与外带", cat:"百货美食", region:"Knightsbridge",
    addr:"87-135 Brompton Rd, Knightsbridge", postcode:"SW1X 7XL", station:"Knightsbridge", walkMin:"2",
    hoursWd:"10:00-21:00", hoursSat:"10:00-21:00", hoursSun:"11:30-18:00（仅 6h）",
    hoursNote:"周日受 Sunday Trading 法限 6h；Food to Order 周一-六 11-18 选邮编配送；The Georgian 下午茶需预订",
    dishes:[{en:"Cured hams, charcuterie & cheeses",cn:"腌制火腿/冷切/奶酪",price:"£10-25"},{en:"Fresh seafood platters",cn:"新鲜海鲜拼盘",price:"£20-40"},{en:"Desserts, teas & gourmet takeaway",cn:"甜点/茶叶/美食外带",price:"£6-20"}],
    perPersonGBP:"£10-40（视摊位）", perPersonCNY:"¥93-372",
    tip:"食品大厅无需小费；餐厅区（The Georgian 等）12.5% 服务费", booking:"食品大厅无需；The Georgian 等餐厅建议预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（The Georgian TA 3.9/1481 点评）",
    koubei:"华人圈认知度极高，微博/知乎/搜狐大量内容。哈罗德美食厅为必打卡点，生蚝/海鲜/派/巧克力陈列琳琅满目。2025 年与泡泡玛特 SKULLPANDA 联名下午茶引发讨论。属高价奢侈品百货美食区，体验>性价比，适合买伴手礼和感受氛围。",
    diet:["素食选项","无麸质"], scene:"走逛（不适合正餐饱腹）",
    imageUrl:"⚠️ 待确认", imageAlt:"Harrods Food Hall", imageCredit:"",
    lat:51.4994, lng:-0.1630, coordApprox:false, trap:false,
    trapNote:"价格昂贵（景点百货内），适合逛+买伴手礼，不适合正餐饱腹；The Georgian 下午茶需提前预订",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.harrods.com/en-ro/c/services/food-to-order",what:"Food Halls 官方页"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2008455-Reviews-The_Harrods_Tea_Rooms-London_England.html",what:"The Georgian TA 3.9/1481 点评"},{url:"https://www.delvaux.cn/zh/boutiques/delvaux-harrods",what:"Harrods 营业时间（一-六 10-21，日 11:30-18）"}]
  },
  {
    id:"cf-fishchips", day:"d5", meal:"dinner",
    nameEn:"Poppies", nameCn:"波派炸鱼薯条",
    cuisine:"英式炸鱼薯条", cat:"英式", region:"Soho",
    addr:"55-59 Old Compton St, Soho", postcode:"W1D 5JN", station:"Tottenham Court Rd / Leicester Square", walkMin:"5",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"1945 年创立；2013-2014 英国最佳炸鱼薯条奖；报纸包裹传统呈现",
    dishes:[{en:"Cod & Chips",cn:"鳕鱼炸鱼薯条",price:"~£10-16（≈¥96）"}],
    perPersonGBP:"£10-16", perPersonCNY:"¥95-150",
    tip:"⚠️ 待确认", booking:"⚠️ 待确认",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"51offer 中文美食帖：2014 年炸鱼薯条奖的赢家，店面设计古典中带着幽默，每一个角落都有特别之处。百度百科收录：1945 年创立，2013-2014 连续获 Seafish UK 英国最佳炸鱼薯条店。华人圈认知度高，属伦敦炸鱼薯条首选打卡，人均约 96 元人民币，报纸包裹传统呈现。Soho 店近 Covent Garden/Leicester Square。",
    diet:[], scene:"赶时间 / 坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Poppies Fish & Chips", imageCredit:"",
    lat:51.5131965, lng:-0.1312269, coordApprox:false, trap:false, trapNote:"",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.51offer.com/article/detail_54034.html",what:"口碑（51offer）"},{url:"https://baike.baidu.com/item/Poppies/63612506",what:"品牌（百度百科）"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Old Compton St W1D 5JN，Nominatim）"}]
  },
  {
    id:"cf-afternoon-tea", day:"d6", meal:"tea",
    nameEn:"Fortnum & Mason — Diamond Jubilee Tea Salon", nameCn:"福南梅森",
    cuisine:"英式下午茶", cat:"下午茶", region:"Piccadilly",
    addr:"181 Piccadilly, Mayfair", postcode:"W1A 1ER", station:"Piccadilly Circus / Green Park", walkMin:"5",
    hoursWd:"商店 10:00-20:00；茶沙龙 4 楼", hoursSat:"10:00-20:00", hoursSun:"12:00-18:00（11:30 起浏览）",
    hoursNote:"1707 年创立，王室御用；Diamond Jubilee Tea Salon 4 楼（女王 2012 揭幕）；末次预订闭馆前 2h；Time Out 2025 最佳下午茶",
    dishes:[{en:"Afternoon tea (sandwiches, scones, cakes)",cn:"下午茶（三明治/司康/蛋糕）",price:"£84起/人"},{en:"Caviar Tea Experience (Golden Oscietra/Beluga)",cn:"鱼子酱下午茶",price:"£165起/人"},{en:"150+ loose-leaf teas",cn:"150余种散叶茶",price:"含于茶费"}],
    perPersonGBP:"£84起", perPersonCNY:"¥781起",
    tip:"12.5% 服务费通常自动加入账单", booking:"需提前预约 fortnumandmason.com 或 020 7734 8040",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认",
    koubei:"知乎/微博/搜狐大量真实口碑：1707 年创立，王室御用，女王亲临的 Diamond Jubilee Tea Salon。中文博主普遍反馈司康饼+凝脂奶油为招牌，茶叶品质顶级，需提前预订。属正统英式下午茶首选，非踩坑。",
    diet:["素食选项","无麸质"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Fortnum & Mason 下午茶", imageCredit:"",
    lat:51.5081856, lng:-0.1381409, coordApprox:false, trap:false,
    trapNote:"需提前预约；价位高端但在正统下午茶中算合理；一楼零售区可买茶/饼干伴手礼",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.fortnumandmason.com/diamond-jubilee-tea-salon",what:"茶沙龙 4 楼+下午茶£84起+预约电话（官网）"},{url:"https://www.fortnumandmason.com/piccadilly",what:"地址 W1A 1ER+商店营业时间（官网）"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Nominatim）"}]
  },
  {
    id:"cf-dintai", day:"d5", meal:"dinner",
    nameEn:"Din Tai Fung", nameCn:"鼎泰丰",
    cuisine:"中餐 / 台湾小笼包", cat:"中餐亚洲", region:"Covent Garden",
    addr:"5-6 Henrietta St, Covent Garden（伦敦确认门店）", postcode:"WC2E", station:"Covent Garden", walkMin:"3",
    hoursWd:"⚠️ 待确认", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"⚠️ 原指南 Center Point（101-103 New Oxford St）门店未核实；伦敦确认店在 Covent Garden；King's Cross 分店 2026-12 新开",
    dishes:[{en:"Xiao Long Bao (18 folds)",cn:"小笼包（18褶）",price:"⚠️ 待确认"},{en:"Spicy pork & vegetable wontons",cn:"红油抄手",price:"⚠️ 待确认"},{en:"Fried rice with pork chop",cn:"排骨炒饭",price:"⚠️ 待确认"},{en:"Shrimp & pork dumplings",cn:"虾肉烧卖",price:"⚠️ 待确认"}],
    perPersonGBP:"£20-35", perPersonCNY:"¥186-326",
    tip:"12.5% 服务费通常自动加入账单", booking:"dintaifung-uk.com 预订",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（Covent Garden TA 3.8/1042 点评）",
    koubei:"⚠️ 待确认 — 鼎泰丰品牌在华人圈认知度极高（全球小笼包代表，18 褶工艺），但伦敦 Covent Garden 分店的具体华人旅客体验帖未检索到。知乎/大众点评有鼎泰丰全球评价讨论，普遍争议：江浙沪人觉得不正宗，但品控稳定。伦敦店人均偏高，适合中国胃 fallback，非踩坑但性价比一般。",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"鼎泰丰 小笼包", imageCredit:"",
    lat:51.5110764, lng:-0.1237582, coordApprox:false, trap:false,
    trapNote:"⚠️ 原指南 Center Point（101-103 New Oxford St）门店未能核实；伦敦确认门店为 Covent Garden（5-6 Henrietta St，TA 3.8）。King's Cross 分店 2026-12 新开。行前到 dintaifung-uk.com 确认门店。",
    queryDate:"2026-09-26",
    sources:[{url:"https://dintaifung-uk.com/",what:"18褶小笼包+King's Cross 2026-12 新开（官网）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d15599297-Reviews-Din_Tai_Fung_Covent_Garden-London_England.html",what:"Covent Garden 门店 TA 3.8/1042 点评"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Henrietta St，Nominatim）"}]
  },
  {
    id:"cf-lanzhou", day:"d5", meal:"dinner",
    nameEn:"Lanzhou Noodle Bar", nameCn:"兰州拉面",
    cuisine:"中餐 / 兰州牛肉拉面", cat:"中餐亚洲", region:"Chinatown",
    addr:"33 Cranbourn St（近 Leicester Square/唐人街）", postcode:"WC2H", station:"Leicester Square", walkMin:"2",
    hoursWd:"⚠️ 待确认（TA 显示 currently open）", hoursSat:"⚠️ 待确认", hoursSun:"⚠️ 待确认",
    hoursNote:"平价面馆，午餐+晚餐",
    dishes:[{en:"Lanzhou beef hand-pulled noodles",cn:"兰州牛肉拉面",price:"£8-12"},{en:"Beef brisket noodle soup",cn:"牛腩面",price:"£8-12"},{en:"Cold noodles / sesame paste noodles",cn:"凉面/麻酱面",price:"£7-10"}],
    perPersonGBP:"£8-12", perPersonCNY:"¥74-112",
    tip:"无需小费（平价面馆）", booking:"无需预订/先到先得",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.8",
    koubei:"网易/什么值得买伦敦平价餐厅帖收录（4.2/5）。另有 Kung Fu Noodle（64 Shaftesbury Ave）大众点评华人口碑更好：伦敦超级火爆的兰州拉面每天满座，牛肉拉面中辣好鲜美，油泼面疯狂打 Call。属唐人街老牌平价面馆，适合快饱腹。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"⚠️ 待确认", imageAlt:"兰州拉面", imageCredit:"",
    lat:51.5120, lng:-0.1280, coordApprox:true, trap:false,
    trapNote:"唐人街老店（21 Wardour St 兰州拉面）品质近年下滑（味精味重）；Kung Fu Noodle（64 Shaftesbury Ave）口碑更稳但需排队；坐标为 Leicester Square 片区参考",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d6580926-Reviews-Lanzhou_Noodle_Bar-London_England.html",what:"地址 33 Cranbourn St+TA 3.8/198 点评"},{url:"https://www.163.com/dy/article/H7CBQK8F05178RJE.html",what:"口碑（网易）"},{url:"https://m.dianping.com/discovery/986502432",what:"口碑（大众点评）"}]
  },
  {
    id:"cf-hotpot", day:"d5", meal:"dinner",
    nameEn:"Little Lamb", nameCn:"小尾羊",
    cuisine:"中式火锅 / 自助", cat:"中餐亚洲", region:"Chinatown",
    addr:"72 Shaftesbury Ave, Soho", postcode:"W1D 6NA", station:"Leicester Square / Piccadilly Circus", walkMin:"3",
    hoursWd:"周一-四 12:00-23:00", hoursSat:"周五-六 12:00-23:30", hoursSun:"12:00-22:30",
    hoursNote:"⚠️ 待官网确认 — 时间来自搜狐；自助火锅，平价饱腹型",
    dishes:[{en:"All-you-can-eat hotpot buffet",cn:"自助火锅",price:"£25-35/人"},{en:"Lamb sliced for hotpot",cn:"涮羊肉",price:"含于自助"},{en:"Sichuan mala broth / clear broth",cn:"麻辣锅底/清汤锅底",price:"含于自助"}],
    perPersonGBP:"£25-40", perPersonCNY:"¥233-372",
    tip:"服务费自愿，惯例 10-12.5%", booking:"电话 +44 20 7287 8078；现场排队亦可",
    googleRating:"⚠️ 待确认", googleReviews:"⚠️ 待确认", taRating:"3.5",
    koubei:"搜狐/微信留学生攻略帖收录：这是一家自助火锅店，在伦敦中国城附近，超好吃不说，还可以吃肉吃到爽。TripAdvisor 中文 91 条点评（3.5 分）。属唐人街 Shaftesbury Ave 上的自助火锅，定位平价饱腹型。注：若追求正宗川味，蜀姐火锅（Holborn，非唐人街）华人口碑更高伦敦最好吃的川渝火锅。",
    diet:["素食选项"], scene:"坐下来",
    imageUrl:"⚠️ 待确认", imageAlt:"Little Lamb 火锅", imageCredit:"",
    lat:51.5118885, lng:-0.1319138, coordApprox:false, trap:false,
    trapNote:"自助火锅定位平价，品质中规中矩；唐人街火锅店普遍游客化，想吃正宗川味建议去 Holborn 蜀姐；⚠️ Nominatim 显示该地址当前营业主体可能变动，行前核实是否仍为小尾羊",
    queryDate:"2026-09-26",
    sources:[{url:"https://www.sohu.com/a/520040751_121124401",what:"地址 W1D 6NA+电话+营业时间（搜狐）"},{url:"https://www.tripadvisor.cn/Restaurant_Review-g186338-d2326439-Reviews-Little_Lamb-London_England.html",what:"TA 3.5/91 点评"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（72 Shaftesbury Ave，Nominatim）"}]
  },
  {
    id:"cf-english-breakfast", day:"d6", meal:"breakfast",
    nameEn:"Regency Café", nameCn:"⚠️ 待确认",
    cuisine:"英式传统全餐 / Greasy Spoon", cat:"英式", region:"Westminster",
    addr:"17-19 Regency St, Westminster", postcode:"SW1P 4BY", station:"Pimlico / St James's Park", walkMin:"8",
    hoursWd:"07:00-15:30", hoursSat:"07:00-15:30", hoursSun:"闭馆（周日休）",
    hoursNote:"1946 年开业；艺术装饰风；《Layer Cake》《Pride》取景地；Yelp 2013 伦敦第 5；No Substitutions 政策",
    dishes:[{en:"The Icon Set Breakfast (egg, bacon, sausage, beans/tomatoes, toast, tea/coffee)",cn:"招牌全英早餐套餐",price:"£9.99"},{en:"Classic omelette & steak-cut chips",cn:"经典蛋饼配薯条",price:"£7.00"},{en:"Full English",cn:"全英早餐",price:"£9-11"}],
    perPersonGBP:"£9-11", perPersonCNY:"¥84-102",
    tip:"柜台点餐自取；无需小费", booking:"无需预订/先到先得；电话 020 7821 6596",
    googleRating:"4.7", googleReviews:"⚠️ 待确认", taRating:"⚠️ 待确认（TA 未显著收录）",
    koubei:"⚠️ 待确认 — Regency Café 为伦敦知名平价英式早餐店（Google 4.7），1946 年开业，艺术装饰风，曾是《Layer Cake》《Pride》取景地；华人社区深度体验帖待补充。",
    diet:["素食选项"], scene:"赶时间",
    imageUrl:"⚠️ 待确认", imageAlt:"Regency Café 艺术装饰风店堂", imageCredit:"",
    lat:51.494002, lng:-0.1320948, coordApprox:false, trap:false,
    trapNote:"平价正宗英早（£9.99 全餐，Google 4.7）；⚠️ 周日闭馆；D6 周六早晨可顺道（近 Westminster/London Eye，Pimlico/St James's Park 站）。想高端英早改 The Wolseley（160 Piccadilly，须预订，£20-30）。",
    queryDate:"2026-09-26",
    sources:[{url:"https://regencycafe.co.uk/",what:"地址 SW1P 4BY+营业时间一-六 07-15:30 日闭+菜品价+Google 4.7（官网）"},{url:"https://nominatim.openstreetmap.org/",what:"地址坐标（Nominatim 精确）"}]
  }
];
